# -*- coding: utf-8 -*-
"""2016 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'cliché': 'n. 陈词滥调',
    'mournfully': 'adv. 哀伤地',
    'never any time to read': '永远没有时间阅读',
    'thornier': 'adj. 更棘手的（thorny 的比较级）',
    'time-management techniques': '时间管理技巧',
    'tips on making time to read': '腾出时间阅读的建议（tip 建议）',
    'at all times': '随时；始终',
    'free up the odd 30 minutes': '腾出零星的 30 分钟（free up 腾出；odd 零星的）',
    'the flywheel of work-related thoughts': '与工作相关的思绪飞轮（flywheel 飞轮）',
    'the last thing you need': '你最不需要的东西',
    'overwhelmingly inclined': '压倒性地倾向于（overwhelmingly 压倒性地）',
    'inclined to interruption': '倾向于被打断（be inclined to 倾向于）',
    "can't be obtained merely": '无法仅仅通过…获得（merely 仅仅）',
    'becoming more efficient': '变得更有效率（动名词短语作主语）',
    'instrumentally': 'adv. 工具性地',
    'as well spent': '被妥善利用（well spent 用得其所）',
    'Immersive reading': '沉浸式阅读（immersive 沉浸的）',
    'goallessness': 'n. 无目标状态',
    'slot it in': '把它塞进去（slot in 插入、安置）',
    'goal-focused': 'adj. 目标导向的',
    'fulfilling': 'adj. 令人满足的',
    'conveyor belt': '传送带',
    'mind-set': 'n. 心态；思维定式',
    'losing yourself in a book': '让自己沉浸在一本书中（lose oneself in）',
    'what does work': '什么方法有效（do 强调）',
    'scheduling regular times': '安排固定的时间（schedule 安排）',
    'fuel the efficiency mind-set': '助长效率心态（fuel v. 助长）',
    'ritualistic behaviour': '仪式化行为（ritualistic 仪式化的）',
    'single-purpose e-readers': '专用电子阅读器（single-purpose 单一用途的）',
    'providing you dip in': '只要你翻阅（providing 假如；dip in 翻阅）',
    'the default state': '默认状态',
    'take care of business': '处理事务',
    'as if': '好像（引导表语从句）',
    'making time to read': '腾出时间阅读',
}
