# -*- coding: utf-8 -*-
"""2016 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'estimate': 'v. 估计',
    'lent red to': '为…增添了红色（lend... to 给…增添）',
    'landscape': 'n. 景观；景色',
    'remain today': '如今仍留存（remain 剩余）',
    'historic range': '历史分布范围（range 分布区）',
    'The crash': '（数量的）骤减（crash 暴跌）',
    'a major reason': '主要原因',
    'formally list': '正式列为（list A as B）',
    'threatened': 'adj. 受威胁的（物种保护等级）',
    'desperate situation': '绝望的境地（desperate 令人绝望的）',
    'Director': 'n. 局长；主任',
    'environmentalists': 'n. 环保人士（environmentalist）',
    'disappointed': 'adj. 失望的',
    'designate': 'v. 指定；把…定名为',
    'crack down on': '打击；镇压',
    'flexibility': 'n. 灵活性',
    'confrontational': 'adj. 对抗性的；冲突的',
    'forging closer collaborations': '建立更紧密的合作（forge 建立）',
    'uneasy with': '对…感到不安',
    'landowners': 'n. 土地所有者（landowner）',
    'prosecute': 'v. 起诉；检举',
    'as long as': '只要（引导条件状语从句）',
    'range-wide': '覆盖整个分布区的（range 分布区）',
    'requires': 'v. 要求（require sb. to do）',
    'habitat': 'n. 栖息地',
    'pay into a fund': '向基金缴款',
    'compensate': 'v. 补偿',
    'set aside': '预留；拨出',
    'interim goal': '中期目标（interim 中期的）',
    'restoring': 'v. 恢复（restore 的动名词）',
    'coalition': 'n. 联盟；联合体',
    'monitoring progress': '监测进展（monitor 监测）',
    "remain in the driver's seat": "保持主导地位（in the driver's seat）",
    'buys the win-win rhetoric': '相信双赢的说辞（buy 此处意为相信；rhetoric 说辞）',
    'block the plan': '阻止该计划（block 阻挠）',
    'challenging': 'v. 质疑（challenge 的现在分词）',
    'goes too far': '走得太远',
    "doesn't go far enough": '做得还不够',
    'giving responsibility for': '把…的责任交给（give responsibility for）',
    'extinction': 'n. 灭绝',
}
