# -*- coding: utf-8 -*-
"""2016 考研英语二 Text 4 —— 重点词释义（key 与 _a/_b/_c 的 bold 完全一致）。"""
GLOSS = {
    'Against a backdrop of': 'prep. 在…的背景下（backdrop 原指舞台背景）',
    'drastic': 'adj. 剧烈的；极端的',
    'road map': 'n. 路线图；规划蓝图',
    'prize': 'v. 珍视；高度重视',
    'milestones': 'n. 里程碑；重大事件（milestone 的复数）',
    'including': 'prep. 包括…在内',
    'agree on': 'v. 就…达成一致',
    'strikingly': 'adv. 显著地；惊人地',
    'fulfilling': 'adj. 令人满足的；有成就感的',
    'prioritize': 'v. 优先处理；把…排在首位',
    'advance': 'v. 推进；促进（事业等）发展',
    'financially secure': 'adj. 经济上有保障的；财务稳定的',
    'maintain': 'v. 坚持认为；主张',
    'suggest': 'v. 表明；暗示（后接宾语从句）',
    'in the aftermath of': 'prep. 在…之后（尤指灾难、战争等之后）',
    'searing': 'adj. 灼热的；（痛苦）强烈的',
    'virtually': 'adv. 几乎；差不多',
    'converge on': 'v. 在…上达成一致；汇聚于',
    'Overwhelming majorities': 'n. 压倒性多数（overwhelming majority 的复数）',
    'get started in life': 'v. 开始人生（起步、踏上社会）',
    'earlier generations': 'n. 更早的几代人；前辈',
    'optimistic': 'adj. 乐观的',
    'tougher climb': 'n. 更艰难的攀登（比喻向上流动更难）',
    'signpost achievements': 'n. 标志性成就（signpost 原指路标）',
    'affordable housing': 'n. 负担得起的住房',
    'considers': 'v. 认为；视为',
    'the climb': 'n. 攀登（比喻为生活奋斗的历程）',
    'tougher': 'adj. 更艰难的（tough 的比较级）',
    'auto technician': 'n. 汽车技师',
    'struggled': 'v. 努力挣扎；费力（去做某事）',
    'graduating from college': 'v. 大学毕业（graduate from 从…毕业）',
    "can't afford": 'v. 负担不起；无力支付',
    'monthly mortgage payments': 'n. 每月的抵押贷款（按揭）还款',
    'rent rooms out': 'v. 把房间出租（rent out 出租）',
    'on my own': 'adv. 独自地；靠自己',
    'Looking back': 'adv. 回首往事；回顾过去',
    'struck': 'adj. 深受触动的；感到震惊的（be struck that...）',
    'comfortable life': 'n. 舒适的生活',
    'completed college': 'v. 读完大学；完成大学学业',
    'grew up': 'v. 长大；成长',
    'middle-class': 'adj. 中产阶级的',
    'college degrees': 'n. 大学学位（college degree 的复数）',
    "don't think": 'v. 不认为（否定转移，否定的是从句）',
    'capable of': 'adj. 有能力做…的；能够…的',
    'anymore': 'adv. （不）再；如今不再',
}
