# -*- coding: utf-8 -*-
"""2017 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'in conjunction with': '与…一起；连同',
    'overlook the possibility': '忽视…的可能性（overlook 忽视）',
    'After all': '毕竟',
    'stay back a year': '推迟一年（stay back 留在原处）',
    'feel natural': '感觉自然',
    "isn't academic": '不是学术性的（academic 学术的）',
    'condemn': 'v. 谴责；否定',
    'good enough reason': '充分的理由',
    'falling behind': '落后（fall behind）',
    'lucrative': 'adj. 赚钱的；高薪的',
    'misconceptions': 'n. 误解（misconception）',
    'hinder': 'v. 阻碍',
    'enhances': 'v. 增强；提升（enhance 的三单）',
    'better prepared for': '为…做了更好的准备',
    'perform better': '表现更好',
    'pushes them ahead': '推动他们前进（push ahead 推进）',
    'struggle with': '与…作斗争；艰难应对',
    'lessen the blow': '减轻冲击（lessen 减轻；blow 打击）',
    'acclimation blunders': '适应过程中的失误（acclimation 适应；blunder 大错）',
    'inherent value': '内在价值（inherent 固有的）',
    'financial impact': '财务影响',
    'end up changing': '最终改变（end up doing）',
    'majors': 'n. 专业（major 的复数）',
    'mandatory': 'adj. 必修的；强制的',
    'a poor understanding': '了解甚少；理解不足',
    'listing one major': '列出一个专业（list 列出）',
    'switching to another': '换到另一个（switch to）',
    'costly': 'adj. 代价高昂的',
    'credits': 'n. 学分（credit）',
    'complete an extra year': '额外完成一年（学业）',
    'nursing school': '护理学院',
    'figure things out': '弄清楚情况（figure out）',
    'prevent stress': '防止压力',
}
