# -*- coding: utf-8 -*-
"""2017 考研英语二 Text 1 —— 重点词释义（key 必须与 _a/_b/_c 里的 bold 完全一致）。"""
GLOSS = {
    'Instead of': '而不是；代替（介词短语，后接名词或动名词）',
    'Olympiad': 'n. 奥林匹克运动会；两届奥运会之间的四年周期',
    'a dozen': '十几个，一打（约十二个）',
    'absurd': 'adj. 荒谬的，荒唐的',
    'accelerating': 'adj. 不断加速的（accelerate 的现在分词作定语）',
    'at least': '至少；起码',
    'bidders': 'n. 申办者，投标者（bidder 的复数）',
    'by contrast': '相比之下；与之相对',
    'common goods': 'n. 公共产品，公共物品',
    'competitor': 'n. 竞争者，对手；参赛者',
    'couches': 'n. 沙发（couch 的复数）',
    'did rise': '确实上升了（did 为强调助动词，加强肯定语气）',
    'dual': 'adj. 双重的，双的',
    'elite athletes': '精英运动员',
    'ethos': 'n. （群体的）精神气质，理念',
    'failed to': '未能做某事（fail to do sth.）',
    'falling': 'v. 下降，跌落（fall 的现在分词）',
    'getting involved in': '参与，涉足（get involved in）',
    'grassroots': 'adj. 草根的，基层的  n. 草根阶层',
    'growing': 'v. 增长，增长中（grow 的现在分词）',
    'halved': 'v. 减半（halve 的过去分词）',
    'happened': 'v. 发生（happen 的过去分词）',
    'in the run-up to': '在……的前夕；在……的准备阶段',
    'inspired': 'v. 激励，鼓舞；启发（inspire 的过去式/过去分词）',
    'intimidating': 'adj. 令人畏惧的，让人望而生畏的',
    'is succeeding': 'v. 正在取得成功（succeed 的现在进行时）',
    'legacy': 'n. 遗产；遗留物',
    'lever': 'v. 撬动；（用杠杆）撬起  n. 杠杆',
    'local park': '当地公园',
    'mixed up': 'v. 混淆，搞混（mix up 的被动形式）',
    'more than': '超过；多于',
    'obesity': 'n. 肥胖（症）',
    'offers': 'v. 提供，给出（offer 的第三人称单数）',
    'opposition': 'n. 反对派，反对党；反对',
    'pave': 'v. 铺设，铺砌',
    'phenomenon': 'n. 现象；非凡的人（或事物）',
    'pledged': 'v. 承诺，保证（pledge 的过去式）',
    'population': 'n. 人口；（全体）居民',
    'presided over': 'v. 主持，掌管（preside over 的过去分词）',
    'produce': 'v. 产生，制造；生产',
    'provision': 'n. 提供，供给；供应品',
    'puffed-out': 'adj. 气喘吁吁的',
    'range from': '从……到……不等；范围从……到……',
    'retrospections': 'n. 回顾，反思（retrospection 的复数）',
    'risen': 'v. 上升，上涨（rise 的过去分词）',
    'set off': 'v. 出发，动身；引爆',
    'squeezing': 'v. 挤压，压榨（squeeze 的现在分词）',
    'staffed': 'v. 为……配备人员（staff 的过去分词）',
    'success': 'n. 成功；成功的事例',
    'successive': 'adj. 连续的，接连的（successive governments 历届政府）',
    'thrive': 'v. 兴旺，繁荣；茁壮成长',
    'time trial': 'n. 计时赛',
    'top talent': '顶尖人才；顶尖选手',
    'volunteers': 'n. 志愿者（volunteer 的复数）',
    'was announced': 'v. 被宣布（announce 的被动语态）',
    'welcomes': 'v. 欢迎，接纳（welcome 的第三人称单数）',
    'world record': '世界纪录',
    'worse': 'adj./adv. 更糟的（地），更差的（地）',
    'worthy': 'adj. 值得的；有价值的；配得上的（此处含讽刺：冠冕堂皇的）',
}
