# -*- coding: utf-8 -*-
"""2017 考研英语二 Text 4 — 重点词释义。"""

GLOSS = {
    'viewed as': '被视为（be viewed as）',
    'frequency of wildfires': '野火发生的频率（frequency 频率）',
    'federal tax dollars': '联邦税收',
    'annual budget': '年度预算',
    'nearly double': '几乎是两倍（double 两倍）',
    'In effect': '实际上；事实上',
    'watershed': 'n. 流域',
    'upkeep': 'n. 维护；保养',
    'fire-prone districts': '火灾高发地区（prone 易于…的）',
    'public funds': '公共资金',
    'puts it': '（as sb. puts it）如某人所说',
    'lost to a wildfire': '毁于野火（be lost to 被…毁掉）',
    'public expenditure perspective': '公共支出角度（expenditure 支出）',
    'magnifying glass': '放大镜',
    'is this OK': '这样可以吗',
    'redirect': 'v. 重新引导；改道',
    'lower-hazard': '危险性较低的（hazard 危险）',
    'corresponding shift': '相应的转变（corresponding 相应的）',
    'views fire': '看待火灾（view v. 看待）',
    'more inclusive': '更具包容性（inclusive 包容的）',
    'the focus has been on': '焦点一直集中在…',
    'greenhouse gases': '温室气体',
    'worsen': 'v. 使恶化；加剧',
    'at the expense of': '以…为代价',
    'equation': 'n. 等式；此处指「综合考虑的各项因素」',
    'go both ways': '双向互动；相互影响',
    'overly simplified': '过于简化的（overly 过度地）',
    'perception': 'n. 认知；看法',
    'becomes very limited': '变得非常有限（limited 有限的）',
    'wholly controlled': '完全被控制（wholly 完全地）',
    'out of necessity': '出于必要',
    'inevitable presence': '不可避免的存在（inevitable 不可避免的）',
    'as safe as possible': '尽可能安全（as... as possible）',
    'disconnected ourselves from': '使自身与…割裂（disconnect from）',
    'tease out': '梳理出；理清',
}
