# -*- coding: utf-8 -*-
"""2017 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'With so much focus on': '由于（人们）过多关注…（with 复合结构）',
    'forget about': '忘记；忽略',
    'suck you in': '把你吸进去；让你上瘾（suck in）',
    'maximal engagement': '最大程度的参与（maximal 最大的）',
    'disengage': 'v. 脱离；抽身',
    'bleed-over': 'n. 渗透；溢出（bleed over 渗入）',
    'tablets': 'n. 平板电脑（tablet）',
    'food-testing exercise': '食物测试练习',
    'verbal': 'adj. 言语的',
    'nonverbal interactions': '非语言互动',
    'a source of tension': '紧张的来源',
    'looking at their emails': '查看电子邮件（现在进行时）',
    'bids for their attention': '争取他们的注意力（make bids for）',
    'wired to': '天生倾向于（be wired to do）',
    'unresponsive': 'adj. 无反应的',
    'disconcerting': 'adj. 令人不安的',
    'cites': 'v. 引用（cite 的三单）',
    'devised by': '由…设计（devise 的过去分词）',
    'blank expression': '面无表情（blank 空白的）',
    'distressed': 'adj. 焦虑的；痛苦的',
    'exquisitely present': '极度专注地陪伴（exquisitely 极好地）',
    'responsive and sensitive': '有回应且敏感（responsive 反应积极的）',
    'oppressive ideology': '压迫性的意识形态（oppressive 压抑的）',
    'neglecting them': '忽视他们（neglect）',
    'just because': '仅仅因为（引导主语从句）',
    'have a break from': '从…中休息一下',
    'get a lot out of': '从…中获益良多',
    'out of the way': '处理掉；不挡路',
    'available to': '能陪伴/可及（be available to）',
}
