# -*- coding: utf-8 -*-
"""2018 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'upmarket grocery chain': '高端食品连锁店（upmarket 高档的）',
    'acquire': 'v. 收购；获得',
    'physical product': '实体产品（physical 实物的）',
    'intricate': 'adj. 复杂精细的',
    'friendships and social lives': '友谊与社交生活',
    'promised': 'v. 承诺（promise 的过去式）',
    'link': 'v. 关联；连接',
    'broke the promise': '违背了承诺（break a promise）',
    'enormously revealing': '极具揭示性（revealing 有启发的）',
    'party whip': '党鞭（政党中负责纪律的官员）',
    'makeup': 'n. 构成；组成',
    'plotting': 'v. 密谋（plot 的现在分词）',
    'not so much': '与其说是…（not so much A but B）',
    'the records of': '…的记录',
    'imbalances of power': '权力失衡（imbalance 失衡）',
    'clumsy': 'adj. 笨拙的',
    'compared to': '与…相比',
    'the pace of change': '变化的速度（pace 速度）',
    'remedied': 'v. 补救（remedy 的过去分词）',
    'vanished': 'v. 消失（vanish 的过去分词）',
    'abuses of power': '权力滥用（abuse 滥用）',
    'conceptual problem': '概念性问题（conceptual 概念的）',
    'as presently interpreted': '按目前的解释（interpret 解释）',
    'financial disadvantage': '财务劣势',
    'customers': 'n. 客户（customer）',
    'dominate': 'v. 主导；支配',
    'to the disadvantage of': '使…处于不利地位',
    'convert': 'v. 转化；转换',
    'for the benefit of': '为了…的利益',
    'farm the bugs': '饲养虫子（farm v. 饲养）',
    'honeydew': 'n. 蜜露（蚜虫分泌的甜液）',
    'yield': 'v. 产生；产出',
    'predatory insects': '捕食性昆虫（predatory 捕食的）',
    'spammers': 'n. 垃圾邮件发送者（spammer）',
    'democratic relationship': '民主的关系（democratic 民主的）',
    'even if': '即使（引导让步状语从句）',
}
