# -*- coding: utf-8 -*-
"""2018 考研英语二 Text 4 — 重点词释义。"""

GLOSS = {
    'putting a premium on': '重视；把…看得重（put a premium on）',
    'recommends': 'v. 建议；推荐（recommend）',
    'without distraction': '不受干扰（distraction 分心）',
    'a number of approaches': '许多方法（approach 方法）',
    'lengthy retreats': '长时间的静修（lengthy 漫长的；retreat 静修）',
    'seizing moments': '抓住时刻（seize 抓住）',
    'stick to it': '坚持下去（stick to 坚持）',
    'deep scheduling': '深度日程安排',
    'interruptions': 'n. 干扰（interruption）',
    'get more done': '完成更多工作',
    'At any given point': '在任何给定时刻',
    'scheduled': 'v. 安排（schedule 的过去分词作宾补）',
    'Once on the calendar': '一旦列入日程（once 引导状语从句）',
    'protect this time': '保护这段时间',
    'rethink': 'v. 重新思考',
    'prioritise': 'v. 确定优先次序（英式拼写）',
    'to-do lists': '待办事项清单',
    'points to': '指出（point to）',
    'undergraduates': 'n. 本科生（undergraduate）',
    'day by day': '逐日；一天天地',
    'assumed': 'v. 以为；假设（assume 的过去式）',
    'the execution of tasks': '任务的执行（execution 执行）',
    'demotivated': 'v. 使失去动力（demotivate 的过去式）',
    'render': 'v. 使成为；使变得',
    'improvisation': 'n. 即兴发挥',
    'reap the best results': '获得最佳结果（reap 收获）',
    'make the most of': '充分利用',
    'embrace downtime': '拥抱休息时间（downtime 停工期、休息时间）',
    'indispensable': 'adj. 不可或缺的',
    'paradoxically': 'adv. 自相矛盾地',
    'counterintuitive': 'adj. 违反直觉的',
    'productivity': 'n. 生产力',
    'operate': 'v. 运作；运转',
    'switch between': '在…之间切换',
    'more efficient': '更有效率（efficient 高效的）',
    'circuits': 'n. 回路；神经回路（circuit）',
    'in order to complete': '为了完成…（in order to 目的状语）',
}
