# -*- coding: utf-8 -*-
"""2018 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'justify': 'v. 为…辩护；证明…有理',
    'as though': '好像；仿佛（引导方式状语从句）',
    'pioneering': 'adj. 开创性的（pioneer 的现在分词作定语）',
    'mechanical memorization': '机械记忆',
    'practical': 'adj. 实用的；实践性的',
    'accepted wisdom': '普遍认同的看法（wisdom 智慧、共识）',
    'overwhelmed by': '被…难住/压垮（be overwhelmed by）',
    'just about everything': '几乎一切事物',
    'graffitied': 'adj. 涂满涂鸦的（graffiti 的过去分词作定语）',
    'discarded chewing gum': '丢弃的口香糖（discarded 被丢弃的）',
    'assembling': 'v. 组装（assemble 的现在分词）',
    'insidious prejudice': '潜在的偏见（insidious 暗中为害的）',
    'inferiority': 'n. 低人一等；次等',
    'vocational education': '职业教育（vocational 职业的）',
    'stereotype': 'n. 刻板印象',
    'academically': 'adv. 在学业上',
    'logical product': '合乎逻辑的产物',
    'economic engine': '经济引擎',
    'job security': '工作保障',
    'evaporated': 'v. 消失；蒸发（evaporate 的过去分词）',
    'More education': '更多的教育（名词短语作主语）',
    'rightfully so': '理所应当（rightfully 正当地）',
    'headlong push': '不顾一切的推动（headlong 轻率的、急速的）',
    'devaluing': 'n. 贬低；贬值（devalue 的动名词）',
    'misses an important point': '忽略了一个要点（miss the point 没抓住要点）',
    'opens more doors': '打开更多大门（open doors 提供机会）',
    'middle-skill jobs': '中等技能工作',
    'high-skill manufacturing': '高技能制造业',
    'adequately trained': '接受了充分培训（adequately 充分地）',
    'vanishing': 'v. 消失（vanish 的现在分词）',
    'staring us in the face': '就摆在我们面前（stare sb. in the face）',
    'a gap in': '…方面的缺口',
    'equipped to': '有能力做…（be equipped to do）',
    'fill that gap': '填补这一缺口',
    'wake-up call': '警钟；警醒信号',
    'one-size-fits-all': '一刀切的；通用的',
    'diversity of gifts': '天赋的多样性（gift 天赋、才能）',
}
