# -*- coding: utf-8 -*-
"""2018 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'fossil fuels': '化石燃料',
    'generate': 'v. 产生；发电',
    'belongs to': '属于（belong to）',
    'picking up momentum': '势头增强（pick up momentum）',
    'account for': '占据（比例）；解释',
    'stems from': '源于（stem from）',
    'farsighted': 'adj. 有远见的',
    'plummeting prices': '暴跌的价格（plummet 骤降）',
    'solar panels': '太阳能电池板',
    'wind turbines': '风力涡轮机',
    'a principal energy source': '主要能源来源（principal 主要的）',
    'power 95 percent': '为 95% 供电（power v. 供电）',
    'takes the lead': '带头；引领（take the lead）',
    'remarkable shift': '显著的转变',
    'for the first time': '首次',
    'generated': 'v. 产生（generate 的过去分词作后置定语）',
    'underlined': 'v. 强调（underline 的过去分词）',
    'the path to': '通往…的道路',
    'dismissed': 'v. 摒弃；贬斥（dismiss）',
    'unreliable': 'adj. 不可靠的',
    'did not play well': '未得到认同（play well with）',
    'dot the fields': '遍布田野（dot 散布于）',
    'tech giants': '科技巨头',
    'put-down for skeptics': '对怀疑者的回击（put-down 贬斥）',
    'storage capacity': '储能容量',
    'around the clock': '全天候；昼夜不停',
    'placing big bets': '下大赌注（place bets on）',
    'electric vehicles': '电动汽车',
    'a rarity': '罕见之物（rarity 稀有）',
    'change the picture': '改变局面',
    'trend lines': '趋势线',
    'spiking': 'v. 飙升（spike 的现在分词）',
    'speeding up': '加快（speed up）',
    'meaningful effect': '有意义的影响',
    'alternative energy': '替代能源',
    'may mean less and less': '可能越来越无关紧要',
}
