# -*- coding: utf-8 -*-
"""2019 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'shade': 'n. 荫凉',
    'the fight against': '与…的斗争',
    'count on': '指望；依靠',
    'soak up': '吸收',
    'carbon dioxide': '二氧化碳',
    'hastening': 'v. 加速（hasten 的现在分词）',
    'emit': 'v. 排放；释放',
    'absorb': 'v. 吸收',
    'a way out of': '摆脱…的办法',
    'striking a subtle balance': '取得微妙的平衡（strike a balance）',
    'flourish': 'v. 繁荣；茁壮成长',
    'carbon sinks': '碳汇（sink 吸收库）',
    'leading the way': '引领方向（lead the way）',
    'figuring out the details': '弄清具体细节（figure out）',
    'aims to double': '旨在加倍（double v. 使翻倍）',
    'thin out': '疏伐；使稀疏',
    'brush': 'n. 灌木丛',
    'temporarily': 'adv. 暂时地',
    'carbon-carrying capacity': '碳承载能力',
    'moisture': 'n. 水分；湿气',
    'restoring': 'v. 恢复（restore 的现在分词）',
    'fend off': '抵御；挡开',
    'rendered': 'v. 使变得（render 的过去分词）',
    'burnable': 'adj. 可燃的',
    'in the event of': '万一发生…；如果…发生',
    'increasingly urgent': '日益紧迫（urgent 紧迫的）',
    'drought': 'n. 干旱',
    'acres': 'n. 英亩（acre）',
    'treat': 'v. 处理（此处指抚育森林）',
    'proceeds of': '…的收益（proceeds 收入）',
    'acreage': 'n. 面积（以英亩计）',
    'prioritize': 'v. 优先处理',
    'locked away': '被固定住（lock away）',
    'solid lumber': '实木木材（lumber 木材）',
    'biofuel': 'n. 生物燃料',
    'under way': '在进行中',
    'accustomed to': '习惯于（be accustomed to doing）',
    'watersheds': 'n. 流域（watershed）',
    'recreation': 'n. 娱乐；消遣',
    'Only recently': '直到最近（置于句首引起倒装）',
    'vital part': '重要作用（vital 至关重要的）',
    'finalized': 'v. 最终确定（finalize 的过去分词）',
    'serve as a model': '作为典范（serve as）',
}
