# -*- coding: utf-8 -*-
"""2019 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'Unlike': 'prep. 与…不同',
    'emerges': 'v. 出现（emerge 的三单）',
    'moral norms': '道德规范（norm 规范）',
    "aren't born knowing": '并非生来就知道（be born doing）',
    'appease': 'v. 安抚；使平息',
    'consciences': 'n. 良心（conscience）',
    'regard': 'v. 认为；看待（regard A to be B）',
    'in the right amount': '适量地',
    'gets a bad rap': '名声不好（get a bad rap）',
    'the emotional equivalent of': '在情感上相当于…（equivalent 等价物）',
    'weighted with': '被…压着的（weighted 过去分词作定语）',
    'outdated': 'adj. 过时的',
    'revival': 'n. 复兴；重新兴起',
    'binary': 'adj. 二元的；非此即彼的',
    'advantageous': 'adj. 有利的',
    'evolved': 'v. 进化（evolve 的过去分词）',
    'alert us to': '提醒我们注意…（alert sb. to）',
    'destructive': 'adj. 破坏性的',
    'prompting': 'v. 促使（prompt 的现在分词）',
    'make up for': '弥补',
    'hold a cooperative species together': '使一个合作型物种凝聚在一起',
    'cooperative species': '合作型物种',
    'social glue': '社会黏合剂',
    'Viewed in this light': '从这个角度看（view in this light）',
    'compensate for': '弥补；补偿',
    'emotional deficiency': '情感上的不足（deficiency 缺乏）',
    'pathways to': '通往…的途径（pathway 路径）',
    'shortfall': 'n. 短缺；不足',
    'rein in': '约束；控制',
    'impulses': 'n. 冲动（impulse）',
    'vice versa': '反之亦然',
    'substitute for': '替代；取代',
    'looked at': '观察；查看（look at）',
    'caregiver assessments': '看护者评估（caregiver 看护者）',
    'transgressions': 'n. 过失；违规（transgression）',
    'handed': 'v. 递给（hand 的过去分词）',
    'anonymous': 'adj. 匿名的',
    'appeared to': '似乎（appear to do）',
    'inclined they were to': '（how inclined...to）他们有多倾向于…',
    'guilt-prone': '容易感到内疚的（-prone 易于…的）',
    'deprivation': 'n. 匮乏；剥夺',
    'good news': '好消息',
    'prosocial': 'adj. 亲社会的',
    'regret': 'n. 后悔；遗憾',
}
