# -*- coding: utf-8 -*-
"""2019 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'complaining of': '抱怨（complain of）',
    'labor shortages': '劳动力短缺',
    'unlikely to stop': '不太可能停止（unlikely 不太可能）',
    'an overhaul of': '对…的全面改革（overhaul 彻底改革）',
    'obstructed': 'v. 阻挠（obstruct 的过去分词）',
    'straightforward visa': '更简便的签证（straightforward 简单的）',
    'will be the losers': '将成为输家',
    'undocumented immigrants': '无证移民（undocumented 无证件的）',
    'characteristics': 'n. 特征（characteristic）',
    'workforce': 'n. 劳动力',
    'predominantly': 'adv. 主要地；占主导地',
    'settled rather than migrating': '定居而非迁徙（migrate 迁徙）',
    'aging': 'v. 变老（age 的现在分词）',
    'At the start of': '在…之初',
    'crop workers': '农作物工人',
    'more than half': '超过一半',
    'picking crops is hard on': '采摘农作物对…很艰难（be hard on）',
    'oft- debated': '经常被辩论的（oft 常，复合形容词）',
    'implausible': 'adj. 不切实际的；难以置信的',
    'Mechanization': 'n. 机械化',
    'not yet': '还没有',
    'labor-intensive': 'adj. 劳动密集型的',
    'strawberries': 'n. 草莓（strawberry）',
    'dairy farms': '奶牛场（dairy 乳品的）',
    'a long way to go': '还有很长的路要走',
    'automated': 'adj. 自动化的',
    'reliant on': '依赖…（be reliant on）',
    'guest workers': '客工；外籍临时工',
    'fill the gaps': '填补缺口',
    'rose sharply': '急剧上升（sharply 急剧地）',
    'more than doubled': '增加了一倍多（double v. 翻倍）',
    'numerical cap': '数量上限（cap 上限）',
    'limited to': '限于…（be limited to）',
    'Even so': '即便如此',
    'complain': 'v. 抱怨',
    'cumbersome': 'adj. 繁琐的',
    'bureaucratic delays': '官僚主义的延误（bureaucratic 官僚的）',
    'on the job': '到岗；在岗',
    'compounded': 'v. 加剧（compound 的过去分词）',
    'raids': 'n. 突击检查（raid）',
    'drive others underground': '迫使其他人转入地下（underground 地下）',
    'raisin and berry growers': '葡萄干和浆果种植者（raisin 葡萄干）',
    'short of labor': '劳动力短缺（be short of）',
    'have responded by': '以…方式回应（respond by doing）',
    'moving operations': '转移业务（operation 经营、业务）',
    'imported': 'v. 进口（import 的过去分词）',
    'Little more than': '仅仅；不过（little more than）',
    'the share of imports': '进口份额（share 份额）',
    'In effect': '实际上',
    'import the workers': '进口工人（import v. 进口）',
}
