# -*- coding: utf-8 -*-
"""2019 考研英语二 Text 4 — 重点词释义。"""

GLOSS = {
    'have a message for you': '有话对你说',
    'beat plastic': '战胜塑料（beat 战胜）',
    'starring in': '主演；参演（star in）',
    'swap out': '替换掉（swap out）',
    'single-use plastic': '一次性塑料',
    'put together': '汇集；整合',
    'enact legislation': '制定法律（enact 颁布）',
    'curb': 'v. 遏制；限制',
    'overarching message': '总体信息（overarching 包罗万象的）',
    'directed at': '针对…（be directed at）',
    'leaving it up to': '把…留给…（leave sth. up to sb.）',
    'limited sense': '有限的认识（sense 认识、判断力）',
    'On their own': '靠自身；独立地',
    'accomplish little': '收效甚微（accomplish 实现）',
    'quitting': 'v. 戒掉；放弃（quit 的现在分词）',
    'detrimental': 'adj. 有害的',
    'moral licensing': '道德许可（因做过好事而自我放行）',
    'allays': 'v. 缓解；减轻（allay 的三单）',
    'centered on': '集中于（be centered on）',
    'hold our governments and industries to account': '追究政府和企业的责任（hold sb. to account）',
    'systemic change': '系统性变革（systemic 系统性的）',
    'acknowledge': 'v. 承认',
    'priority': 'n. 优先事项',
    'expect it to be': '期望它是…（expect sth. to be）',
    'latest book': '最新的著作',
    'Wellesley College professor': '韦尔斯利学院教授',
    'collectively': 'adv. 集体地',
    'structural': 'adj. 结构性的',
    'implementing policy': '实施政策（implement 实施）',
    'altogether': 'adv. 完全地',
    'eliminate': 'v. 消除',
    'incentive-based': '基于激励的（incentive 激励）',
    'trash disposal': '垃圾处理（disposal 处理）',
    "isn't saying": '并不是说（say 后接省略 that 的宾语从句）',
    'caring about': '关心（care about）',
    'too slow': '太慢（too... to 结构）',
    'widespread behavior': '广泛的行为（widespread 普遍的）',
    'writing off': '否定；一笔勾销（write off）',
    'putting things into perspective': '正确看待事物（put... into perspective）',
    "don't have time to wait": '没有时间等待',
    'progressive policies': '进步的政策（progressive 进步的）',
    'rein in': '约束；管束',
    'engaged citizens': '积极参与的公民（engaged 参与的）',
}
