# -*- coding: utf-8 -*-
"""2020 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'It is true that': '…是真的（it 形式主语 + that 主语从句）',
    'publicly traded': '公开上市的（上市公司）',
    'by varying estimates': '根据不同的估算（varying 不同的）',
    'typical CEO': '典型/普通的 CEO',
    'The best model for understanding': '理解…的最佳模型',
    'that of limited CEO talent': '（that 代指 model）CEO 人才有限的模型',
    'highest-earning': '收入最高的（复合形容词）',
    'dynamic elements': '有活力的要素（dynamic 有活力的）',
    'upped their game': "提升了水平（up one's game）",
    'relative to': '相对于；与…相比',
    'at least for': '至少对于…而言',
    'simply being able to': '仅仅是能够…（动名词短语）',
    'a good sense of': '对…的良好认识/判断力',
    'trade in': '在…中交易（trade in markets）',
    'public relations': '公共关系（公关）',
    'slipup': 'n. 小失误；小差错',
    'globalized': 'adj. 全球化的',
    'supply chains': '供应链',
    'mind-boggling': 'adj. 令人难以置信的；惊人的',
    'virtually': 'adv. 几乎；实际上',
    'one way or another': '以这样或那样的方式',
    'Beyond this': '除此之外',
    'day-to-day work': '日常工作',
    'ripping people off': '剥削他人（rip sb. off 敲竹杠）',
    'corporate governance': '公司治理',
    'rigorous': 'adj. 严格的；规范的',
    'principally': 'adv. 主要地',
    'corporate interest': '公司利益',
    'tough jobs': '艰难的工作',
    'cozy insider picks': '内部亲信人选（cozy 亲密舒适的；insider 内部人）',
    'depredation': 'n. 掠夺；劫掠',
    'at the expense of': '以…为代价',
    'tie CEO pay to': '把 CEO 薪酬与…挂钩（tie A to B）',
    'build up': '建立；积累',
}
