# -*- coding: utf-8 -*-
"""2020 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'attuned to': '对…敏感/适应（be attuned to）',
    'cooperate with': '与…合作',
    'extends to': '延伸到；适用于（extend to）',
    'non-living beings': '非生命体',
    'whether': 'conj. 是否（引导宾语从句）',
    'housed': 'v. 安置；让…居住（house 的过去式）',
    'asocial': 'adj. 不合群的；不善社交的',
    'minimalist': 'adj. 极简的',
    'resembling': 'v. 像；类似于（resemble 的现在分词）',
    'followed': 'v. 跟随（follow 的过去式）',
    'trapped': 'adj. 被困的（过去分词作定语）',
    'Meanwhile': 'adv. 与此同时',
    'forwards and backwards': '前后（方向状语）',
    'trapped the robots': '把机器困住（trap 困住）',
    'by pressing a lever': '通过按压杠杆（by + 动名词）',
    'trials': 'n. 试验；尝试（trial 的复数）',
    'more likely': '更可能（be likely to do）',
    'perceived': 'v. 认为；视为（perceive A as B）',
    'genuine social being': '真正的社交生物（genuine 真正的）',
    'bonded': 'v. 建立情感联系（bond with）',
    'communal exploring': '共同探索（communal 公共的、共同的）',
    'return the favour': '回报这份恩惠（return the favour）',
    'get trapped': '被困住（get + 过去分词表被动）',
    'reciprocal help': '互惠帮助（reciprocal 相互的）',
    'direct reciprocity': '直接互惠（reciprocity 互惠）',
    'readiness': 'n. 意愿；准备就绪',
    'given its minimal design': '考虑到其极简设计（given 考虑到）',
    'the same size as': '与…尺寸相同（the same... as）',
    'resembled': 'v. 像（resemble 的过去式）',
    'assumed': 'v. 以为；假设（assume 的过去式）',
    'scent': 'n. 气味',
    'helped with the research': '协助了这项研究',
    'how sensitive': '多么敏感（how 引导宾语从句）',
    'social cues': '社交线索（cue 提示、线索）',
    'tend to treat': '倾向于把…当作（tend to do）',
    'fellow beings': '同类；同伴（fellow 同类的）',
    'fascinated by': '被…吸引/着迷（be fascinated by）',
    'it turns out': '事实证明（it turns out that 形式主语句型）',
}
