# -*- coding: utf-8 -*-
"""2020 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'hailed as': '被誉/称赞为（hail A as B）',
    'rolled out': '推出；发布（roll out）',
    'ambitious restrictions': '雄心勃勃的限制措施',
    'suspended': 'v. 暂停（suspend 的过去式）',
    'demise': 'n. 终止；消亡',
    'centrepiece': 'n. 核心内容（英式拼写）',
    'opposition to': '对…的反对',
    'overruled': 'v. 推翻（overrule 的过去式）',
    'levying fines': '征收罚款（levy 征收）',
    'at best': '充其量；最多也不过',
    'pointed reminder': '尖锐的提醒（pointed 尖锐的）',
    'patchwork': 'n. 拼凑之物；拼凑方案',
    'characterises': 'v. 是…的特征（英式拼写，characterise 的三单）',
    'vulnerable': 'adj. 易受攻击的；脆弱的',
    'tackle': 'v. 应对；处理',
    'inevitably': 'adv. 不可避免地',
    'rather than': '而不是',
    'toxic pollution': '有毒污染（toxic 有毒的）',
    'reversal': 'n. 逆转；反转',
    'ultra-low emission zone': '超低排放区',
    'mayoral election': '市长选举（mayoral 市长的）',
    'spark intense opposition': '引发强烈反对（spark 引发）',
    'motorists': 'n. 驾车者（motorist）',
    'useless': 'adj. 无用的',
    'Far from it': '远非如此（省略句）',
    'levers': 'n. 手段；杠杆（lever）',
    'safeguard': 'v. 保护；捍卫',
    'in the face of': '面对…',
    'deliver': 'v. 带来；实现（deliver improvements 带来改善）',
    'health benefits': '健康益处',
    'do so much': '能做的不多（can only do so much 能力有限）',
    'far bigger than': '远比…大',
    'have failed to': '未能做…（fail to do）',
    'into compliance': '使…合规（bring... into compliance）',
    'enforce existing regulations': '执行现有法规（enforce 执行）',
    'low speed limits': '低速限制',
    'minimise': 'v. 使最小化（英式拼写）',
    'insist': 'v. 坚持要求（insist that (should) do）',
    'clean up': '清理；整治',
}
