# -*- coding: utf-8 -*-
"""2020 考研英语二 Text 4 — 重点词释义。"""

GLOSS = {
    'give or take': '上下浮动；大约',
    'the attention has been rising': '关注度一直在上升（现在完成进行时）',
    'hit the streets': '走上街头（找工作）',
    'labor market': '劳动力市场',
    'hiring': 'v. 招聘（hire 的现在分词）',
    'conducted by': '由…进行（过去分词短语作后置定语）',
    'cubicles': 'n. 办公隔间（cubicle）',
    'differ from': '与…不同',
    'entitled': 'adj. 「有权利意识的」（此处为贬义标签）',
    'catchwords': 'n. 关键词；流行语（catchword）',
    'clear-eyed': 'adj. 目光清醒的；头脑清醒的',
    'pragmatists': 'n. 实用主义者（pragmatist）',
    'economic train wreck': '经济崩溃（train wreck 原义火车失事）',
    'impressionable': 'adj. 易受影响的',
    'life savings': '毕生积蓄',
    'taking any chances': '冒险（take chances）',
    'assuage': 'v. 缓解；减轻',
    'anxious urgency': '焦虑的紧迫感',
    'stand at': '（数值）处于…（stand at a record...）',
    'Federal Reserve': '（美国）联邦储备委员会',
    'graduating seniors': '应届毕业生',
    'with a job in mind': '心中有工作（考虑就业）',
    'desirable trait': '令人向往的特质（trait 特质）',
    'secure employment': '稳定的就业（secure adj. 稳固的）',
    'job security': '工作保障',
    'dedicated to a cause': '致力于某项事业（dedicated 专注的）',
    'the greater good': '更大的利益；公益',
    'a big change from': '与…相比的巨大变化',
    'Associate Director': '副主任；副总监',
    'conducts regular': '定期进行（conduct 进行）',
    'certainty and stability': '确定性和稳定性',
    'gig economy': '零工经济',
    'risk averse': '规避风险的（averse 反对的）',
}
