# -*- coding: utf-8 -*-
"""2021 考研英语二 Text 4 — 重点词释义。每个 bold 必须有对应条目。"""
GLOSS = {
    'based on first impressions': '基于第一印象（based on 根据）',
    'thin slices': '薄片（此处指「薄片体验」——极短的印象片段）',
    'extraneous': 'adj. 无关的；多余的',
    'In one study of': '在一项关于…的研究中',
    'the late psychologist': '已故心理学家（late 此处指「已故的」）',
    'asked participants to': '要求参与者做…（ask sb. to do）',
    'correlated strongly with': '与…高度相关（correlate with）',
    'end-of-semester': 'adj. 学期末的（复合形容词）',
    'count backward from': '从…倒数（count backward 倒数）',
    'by nines': '每次减 9（by 表增量幅度）',
    'occupying': 'v. 占用（occupy 的现在分词，作伴随状语）',
    'just as accurate': '同样准确（just as… 同样地）',
    'demonstrating': 'v. 证明；表明（现在分词作结果状语）',
    'intuitive nature': '直觉性质（intuitive 直觉的）',
    'Critically': 'adv. 关键的是（评注性状语）',
    'spend a minute writing down': '花一分钟写下（spend time doing）',
    'before giving': '在给出…之前（before + 动名词）',
    'dropped dramatically': '急剧下降（dramatically 急剧地）',
    'suspected': 'v. 怀疑；猜想（suspect，后接宾语从句）',
    'focused them on': '使他们专注于（focus on）',
    'rather than': '而不是；而非',
    'when participants watched': '当参与者观看…时（时间状语从句）',
    'similar interference': '类似的干扰（interference 干扰）',
    'whether they were': '他们是…还是…（whether 引导宾语从句）',
    'Other research shows': '其他研究表明（show 后接宾语从句）',
    'detecting deception': '识别欺骗（detect 察觉；deception 欺骗）',
    'instead of reflection': '而非反思（instead of 而不是）',
    "It's as if": '就好像…（as if 引导比喻/虚拟）',
    'driving a stick shift': '开手动挡车（stick shift 手动换挡）',
    "can't remember what": '记不住在做什么（what 引导宾语从句）',
    'go on automatic pilot': '进入自动驾驶模式（automatic pilot 自动驾驶；喻指不假思索）',
    'Much of': '大部分的…（much of + 不可数名词）',
    'Thinking too much': '思考过多（动名词短语作主语）',
    'harm': 'v. 损害；伤害',
    'form preferences': '形成偏好（preference 偏好）',
    'aligned better with': '与…更一致（align with 对齐、一致）',
    'rationale': 'n. 基本理由；逻辑依据',
    'made car-buying decisions': '做出购车决策（make decisions）',
    'objectively better': '客观上更好（objectively 客观地）',
    'only if the decision was complex': '只有当决策复杂时（only if 只有…才）',
    "unleashed": 'v. 释放（unleash 的过去分词，被动语态）',
    'in certain circumstances': '在某些情况下（circumstance 情况）',
    'completed a battery of': '完成了一组/一系列…（a battery of 一套）',
    'tapped reflective thinking': '利用了反思性思维（tap 利用、开发）',
    'figures of speech': '修辞手法（figure of speech 修辞格）',
    'rated the degree': '评估…的程度（rate 评估）',
    'to which they had used': '他们使用…的程度（介词+which 定语从句）',
    'Use of their gut': '对直觉的运用（gut 直觉、本能）',
    'hurt their performance': '损害了他们的表现（hurt 损害）',
    'on the rest': '在其余的（任务）上',
    'the heart is smarter than': '心灵比头脑更聪明（heart 与 head 对举）',
}
