# -*- coding: utf-8 -*-
"""2021 Text 2 —— 加粗词/词组的悬浮释义。每个 bold 必须有释义。"""

GLOSS = {
    'global population': '全球人口',
    'predicted to hit': '预计达到（predict 的过去分词；hit 达到）',
    'keep pace': '跟上；保持同步（keep pace with）',
    'food security': '粮食安全',
    'making headlines': '登上头条；成为新闻（headline n. 头条）',
    'talking point': '话题；谈资',
    'particular reason': '特殊原因（particular adj. 特别的）',
    'Brexit': 'n. 英国脱欧（Britain + exit）',
    'seen by some': '被一些人视为（be seen as 被视为）',
    'reverse': 'v. 扭转；逆转',
    'importing food': '进口食品（import v. 进口）',
    'produces': 'v. 生产（produce 的第三人称单数）',
    'down from': '低于；从…下降（down from 较之前下降）',
    'in the late 1980s': '在 20 世纪 80 年代末',
    'self-sufficiency': 'n. 自给自足（self- 自我 + sufficient 充足的）',
    'the argument goes': '有观点认为；照这种说法（插入语）',
    'boost': 'v. 提振；提高',
    'political sovereignty': '政治主权（sovereignty n. 主权）',
    'Sounds great': '听起来不错',
    'feasible': 'adj. 可行的；行得通的',
    'vision': 'n. 愿景；远景',
    'According to a report': '根据一份报告（according to 根据）',
    'total land area': '国土总面积（land area 土地面积）',
    'associated with': '与…相关；与…联系在一起',
    'meat and dairy': '肉类和乳制品（dairy n. 乳制品）',
    'supplies': 'v. 供应（supply 的第三人称单数）',
    'consumed': 'v. 被消费（consume 的过去分词）',
    'livestock farms': '畜牧场（livestock n. 牲畜）',
    'allow us to cover': '使我们能够满足（allow + 宾语 + to do）',
    'caveats': 'n. 警告；保留意见（此处指需说明之处）',
    'grave': 'adj. 严峻的；严重的',
    'self- sufficient': 'adj. 自给自足的（原文提取带空格）',
    'drastically reduce': '大幅减少（drastically adv. 急剧地）',
    'farm more intensively': '更集约化地耕作（intensively adv. 密集地）',
    'factory-style': 'adj. 工厂式的',
    'switching to': '转向；切换到（switch to）',
    'plant-based diet': '以植物为主的饮食（plant-based 植物性的）',
    'There is a good reason': '有个充分的理由',
    'dominated by': '由…主导；以…为主（dominate v. 主导）',
    'animal husbandry': '畜牧业（husbandry n. 畜牧业）',
    'on a commercial basis': '以商业化的方式（on a ... basis 基于…基础）',
    'suitable for': '适合…的（suitable adj. 合适的）',
    'crop-growing': 'n. 种作物；作物种植',
    'occupied': 'v. 被占据（occupy 的过去分词）',
    'arable fields': '耕地（arable adj. 可耕的）',
    'Even if': '即使；哪怕（引导让步状语从句）',
    'converted': 'v. 转变；改造（convert 的过去式）',
    'fruit and veg': '果蔬（vegetables 的口语缩写）',
    'nature reserves': '自然保护区（reserve n. 保护区）',
    'home-grown': 'adj. 本土种植的；自家种的',
    'extreme measures': '极端的措施',
    'fresh produce': '新鲜农产品（produce n. 农产品）',
    'look for the space': '寻找空间（space 此处指用地）',
    'grains': 'n. 谷物（grain 的复数）',
    'provide us with': '为我们提供（provide sb with sth 双宾语）',
    'calorie intake': '卡路里摄入（intake n. 摄入量）',
}
