# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
GLOSS = {
    'When': 'conj. 当…时（此处引导时间状语从句）',
    'bought': 'v. 购买（buy 的过去式）',
    'attracting considerable buzz': '引起相当大的轰动/关注（attract buzz 引起热议）',
    'dominates': 'v. 占据主导地位；支配（dominate 的三单）',
    'represented': 'v. 代表；意味着（represent 的过去式）',
    'designed from the ground up': '从零开始设计（from the ground up 从头、彻底地）',
    'scrapped': 'v. 废弃；废弃不用（scrap 的过去分词）',
    'after': 'conj. 在…之后（此处引导时间状语从句）',
    'said': 'v. 说；表示（say 的过去式，此处为引述动词）',
    'stayed on': '留下来；继续留存（stay on 留下）',
    'making them': '使它们成为…（make 的现在分词作结果状语）',
    'acqui-hires': 'n. 「收购即招聘」——大公司收购初创企业以获取其人才',
    "To Microsoft's critics": '在微软的批评者看来（to 表"对于"）',
    'remorseless': 'adj. 无情的；冷酷的',
    'chew up': '吞噬；毁坏（chew up 原义"嚼碎"，喻指吞并）',
    'complained': 'v. 抱怨；感叹（complain 的过去式）',
    'a partner at': '…的一名合伙人（partner 合伙人）',
    'putting an end to': '终结；结束（put an end to 制止）',
    'declined to comment': '拒绝置评（decline 拒绝）',
    'depends on': '依赖于；取决于（depend on）',
    'selling': 'v. 出售（sell 的现在分词，此处动名词作宾语）',
    'mixed feelings': '复杂的心情；喜忧参半（mixed 复杂的、矛盾的）',
    'good for': '对…有益；有利于',
    "I don't know": '我不知道',
    'The US Federal Trade Commission': '美国联邦贸易委员会（简称 FTC）',
    'find the answer': '找到答案',
    'asked': 'v. 要求；询问（ask 的过去式）',
    'for information about': '关于…的信息（for 表对象）',
    'over the past decade': '在过去十年中（over 表时间跨度）',
    'Although only a research project': '尽管还只是一个研究项目（although 引导让步状语从句）',
    'raised the prospect': '引发了…的可能性（raise the prospect of 引起…前景/可能）',
    'beyond their reach': '超出它们的管辖/触及范围（beyond one\'s reach 够不着）',
    'Given': 'prep. 考虑到；鉴于（given 引导分词独立结构作状语）',
    'rifling through': '仔细审查；翻查（rifle through 快速翻看、搜查）',
    'beside the point': '无关紧要；离题（介词短语作表语）',
    'Between them': '在它们之间；合计（between 表合计分配）',
    'an average of': '平均…（an average of 平均达）',
    'a drop in the ocean': '沧海一粟；微不足道（固定比喻）',
    'critics say': '批评者称（say 后接省略 that 的宾语从句）',
    'buy': 'v. 买下；收购',
    'gain momentum': '获得发展势头；积聚动力（momentum 势头）',
}
