# -*- coding: utf-8 -*-
"""2021 Text 1 —— 加粗词/词组的悬浮释义。每个 bold 必须有释义。"""

GLOSS = {
    'Reskilling': 'n. 再培训；技能再训练（re- 重新 + skill 技能）',
    'buzzword': 'n. 流行词； buzz words 行业热词',
    'requirement': 'n. 要求；必要条件',
    'would-be': 'adj. 潜在的；未来的（would-be workers 潜在劳动者）',
    'left behind': '被落下；掉队（leave behind 的过去分词）',
    'moving into': '进入；步入（move into）',
    'in demand': '有需求的（jobs in demand 需求岗位）',
    'rapidly': 'adv. 迅速地',
    'as will': '…也是如此（as 引导的倒装省略结构，= as the requirements will change）',
    'Research by the World Economic Forum': '世界经济论坛的研究',
    'finds': 'v. 发现；表明（find 的第三人称单数）',
    'on average': '平均而言',
    'core skills': '核心技能',
    'timeline': 'n. 时间线；时间跨度',
    'thorny': 'adj. 棘手的；多刺的（比喻难解决）',
    'For individual companies': '对单个公司而言',
    'temptation': 'n. 诱惑；诱惑物',
    'let go of': '解雇；放手（此处指裁员）',
    'no longer in demand': '不再有需求的',
    'replace': 'v. 替换；取代',
    'That does not always happen': '情况并非总是如此',
    'gold standard': 'n. 黄金标准；典范（比喻最佳实践）',
    'massive': 'adj. 巨大的；大规模的',
    'rather than': '而不是；与其…不如（表对比）',
    'fire-and-hire': '解雇再招聘（fire 解雇 + hire 雇佣）',
    'Other companies including': '包括…在内的其他公司（including 现在分词作后置定语）',
    'pledged': 'v. 承诺；保证（pledge 的过去式）',
    'create their own plans': '制定自己的计划',
    'skills mismatch': '技能错配（mismatch n. 不匹配）',
    'broader economy': '更广泛的经济（体）',
    'turns to': '转向；求助于（turn to）',
    'Efforts': 'n. 努力；举措（effort 的复数）',
    'arguably': 'adv. 可以说；按理说',
    'languid': 'adj. 迟缓的；无精打采的',
    'begging for': '恳求；乞求（beg for）',
    'unemployment': 'n. 失业（状态）',
    'With the pandemic': '随着疫情（的到来）',
    'indeed': 'adv. 确实；的确（强调肯定）',
    'at 3.5 per cent and 5.5 per cent': '分别为 3.5% 和 5.5%',
    'generational lows': '几代人以来的最低点',
    'worker shortages': '劳动力短缺',
    'As of May': '到五月为止；截至五月',
    'spiked up': '飙升；急剧上升（spike 原指尖峰）',
    'although': 'conj. 尽管；虽然（引导让步状语从句）',
    'disappeared': 'v. 消失（disappear 的过去分词）',
    'In the medical field': '在医疗领域',
    'obvious example': '明显的例子',
    'meant': 'v. 意味着（mean 的过去式）',
    'personnel': 'n. 人员；员工（统称）',
    'Of course': '当然；自然',
    'unemployed': 'adj. 失业的',
    'train': 'v. 培训；训练',
    'no matter who': '无论谁（= whoever，引导让步状语）',
    'even if': '即使；哪怕（引导让步状语从句）',
    'close that gap': '弥合那种差距（gap n. 差距）',
    'to the benefit of': '使…受益；对…有利',
    'That seems to be': '似乎就是…；看来是（the case 情况）',
    'When forced to furlough': '当被迫让…休假时（furlough v. 强制休假；省略主语和 be）',
    'decided to start up': '决定启动（start up 开办、启动）',
    'retraining program': '再培训项目',
    'laid-off': 'adj. 下岗的；被解雇的（lay off 的过去分词）',
    'collective': 'adj. 集体的；共同的',
    'involved': 'v. 涉及；包含（involve 的过去式）',
}
