# -*- coding: utf-8 -*-
"""2022 Text 2 —— 加粗词/词组的悬浮释义。每个 bold 必须有释义。"""

GLOSS = {
    'opting': 'v. 选择；决定（opt 的现在分词，opt to do 选择做）',
    'well into retirement': '到退休很久之后（well into 远到…之后）',
    'upend': 'v. 颠覆；推翻（使颠倒）',
    'workforce model': '劳动力模式；用工模式',
    'at least 40': '至少 40 岁（at least 至少）',
    'plan to': '计划做（plan to do）',
    'prepare for': '为…做准备',
    'a longer life': '更长的寿命',
    'Even more surprising': '更令人惊讶的是（评注性表语，主句倒装）',
    'unretirees': 'n. 不退休者（新造词，指退休后继续工作的人）',
    'settle down': '安顿下来；定居',
    'the survey showed': '调查显示（survey n. 调查）',
    'culprit': 'n. 罪魁祸首；原因（口语化，此处指"原因"）',
    'unretirement': 'n. 不退休（新造词，指退休后继续工作的状态）',
    'according to the study': '根据该研究（according to 根据）',
    'personal fulfillment': '个人成就感；自我实现',
    'such as': '例如；诸如（引出同位语列举）',
    'avoiding depression': '避免抑郁（avoid v. 避免；depression n. 抑郁）',
    'respondents': 'n. 受访者；调查对象（respond 的名词）',
    'once retired': '一旦退休（once 引导省略的时间状语从句）',
    'keep mentally fit': '保持精神健康（mentally 精神上；fit 健康）',
    'tied to': '与…有关；受制于（be tied to）',
    'making ends meet': '维持生计；收支相抵（固定搭配）',
    'evolving': 'v. 逐渐发展；演变（evolve 的现在分词）',
    'senior manager': '高级经理；资深经理',
    'finances': 'n. 财务；财政（finance 的复数）',
    'driving': 'v. 驱使；推动（drive 的现在分词）',
    'past retirement': '超过退休年龄；退休之后',
    'patterns': 'n. 模式；方式（pattern 的复数）',
    'living longer': '活得更长（life expectancy 上升）',
    'The share of the population': '人口占比（share n. 份额）',
    'up 32%': '增长了 32%（up 作表语，表增长）',
    'the prior year': '前一年（prior adj. 之前的）',
    'Census Bureau': 'n. 人口普查局（美国官方统计机构）',
    'That': '代词：那；它（此处指上文的比例）',
    'up 30.2%': '增长了 30.2%',
    'since 2010': '自 2010 年以来（since 表起点）',
    'fastest-growing': 'adj. 增长最快的',
    'segment': 'n. 群体；部分；细分市场',
    'boomers': 'n. 婴儿潮一代（baby boomers 的简称）',
    'previous generations': '前几代人（previous adj. 先前的）',
    'has doubled': '翻了一番；翻倍（double v. 翻倍）',
    'over the past three decades': '在过去三十年里',
    'in the workforce': '在劳动力队伍中；在职',
    'all-time low': '历史最低点（all-time 空前的）',
    'Because of': '因为；由于（because of + 名词）',
    'boosting': 'v. 提高；增加（boost 的现在分词）',
    'preserve': 'v. 保护；保存',
    'nest eggs': 'n. 养老金；储备金（比喻退休储蓄）',
    'surveyed': 'v. 调查；抽样调查（survey 的过去式）',
    'Six in 10': '十分之六（= 60%）',
    'in anticipation of': '预期；为迎接…做准备',
    'Among the most popular ways': '在最流行的方式之中（among 在…之中）',
    'reducing': 'v. 减少（reduce 的现在分词）',
    'securing': 'v. 获得；购买（secure 此处为"取得"，如买保险）',
    'maximizing': 'v. 最大化（maximize 的现在分词）',
    'retirement accounts': '退休账户（如 401k 等）',
    'Unfortunately': 'adv. 不幸地；遗憾的是',
    'opting to work': '选择工作（opt to do 选择做）',
    'making ends meet': '维持生计；收支相抵',
    'later years': '晚年；退休后的岁月',
    'suggested': 'v. 建议；提出（suggest 的过去式）',
    'preretirees': 'n. 即将退休的人（pre- 前/预备）',
    'financial adviser': '财务顾问',
    'long-term': 'adj. 长期的',
    'challenging': 'adj. 有挑战性的；困难的',
    'getting married': '结婚（get married 结婚）',
    'starting a family': '组建家庭；生儿育女',
    'an emotional one': '一个情感上的决定（one 指代 decision）',
    'believe': 'v. 认为；相信',
    "can't retire": '无法退休（can not retire 的缩略）',
}
