# -*- coding: utf-8 -*-
"""2022 Text 4 —— 加粗词/词组的悬浮释义。每个 bold 必须有释义。"""

GLOSS = {
    'Although': 'conj. 尽管；虽然（引导让步状语从句）',
    'ethics classes': '伦理课程（ethics n. 伦理；道德哲学）',
    'unsure': 'adj. 不确定的（be unsure if 不确定是否）',
    'behavior': 'n. 行为；举止',
    'contrived': 'adj. 人为设计的；做作的（contr 的过去分词作形容词）',
    'self-reports': 'n. 自我报告（self-report 的复数，指受访者自述）',
    'published in Cognition': '发表在《认知》期刊上（Cognition 为心理学学术期刊）',
    'found': 'v. 发现；表明（find 的过去式）',
    'real-world': 'adj. 真实世界的；现实中的',
    'lasting effects': '持久的影响（lasting adj. 持久的；effect n. 影响）',
    'investigated': 'v. 调查；研究（investigate 的过去式）',
    'impact': 'n. 影响（impact on 对…的影响）',
    'eating meat': '吃肉',
    'for three reasons': '出于三个原因',
    'co-author': 'n. 共同作者（co- 共同）',
    'philosopher': 'n. 哲学家',
    'variable': 'adj. 多变的；不稳定的',
    'easily measurable': '易于测量的（measurable adj. 可测量的）',
    'ethics literature': '伦理学文献',
    'environmental harm': '环境危害',
    'animal suffering': '动物痛苦',
    'read an article': '阅读一篇文章',
    'optionally': 'adv. 可选地；自愿地',
    'joined': 'v. 参加；加入（join 的过去式）',
    'discussion': 'n. 讨论',
    'focused on': '专注于；聚焦于（focus on）',
    'charitable giving': '慈善捐赠（charitable adj. 慈善的）',
    'unknown to the students': '学生不知情的（unknown to 不为…所知）',
    'anonymized': 'adj. 匿名的（anonymize 的过去分词）',
    'meal-card purchases': '餐卡购买记录（meal-card 餐卡；原文提取带空格）',
    'receipts': 'n. 收据；小票（receipt 的复数）',
    'predicted': 'v. 预测（predict 的过去式）',
    'intervention': 'n. 干预；介入',
    'previously': 'adv. 先前；以前',
    'differ from': '与…不同（differ v. 不同）',
    'blood donation': '献血（donation n. 捐赠）',
    'among student subjects': '在学生受试者中（subject 此处指实验对象）',
    'discussed meat ethics': '讨论了肉类伦理',
    'decreased': 'v. 下降；减少（decrease 的过去式）',
    'held steady': '保持稳定（hold steady 保持不变）',
    'remained': 'v. 保持；仍然是（remain 的过去式）',
    'the other group': '另一组（对照组）',
    'pretty large': '相当大的（pretty 此处为副词"相当"）',
    'pretty small': '相当小的',
    'Psychologist': 'n. 心理学家',
    'not involved': '未参与（be not involved in 没有卷入）',
    'rule out': '排除；否定（rule out 排除可能性）',
    'confounding variable': '混淆变量（confounding adj. 混淆的；variable n. 变量）',
    'if real': '如果（它是）真的（if real = if it is real，省略）',
    'reversible': 'adj. 可逆的；可逆转的（reverse 的形容词）',
    'nudge': 'n. 推动；助推（行为经济学中指微小干预）',
    'Easy come, easy go': '来得容易去得也快（谚语，指易得易失）',
    'suspects': 'v. 怀疑；猜想（suspect 的第三人称单数）',
    'social influence': '社会影响',
    'classmates': 'n. 同学（classmate 的复数）',
    'teaching assistants': '助教（teaching assistant 的复数）',
    'vegetarianism': 'n. 素食主义',
    'Second': 'adv. 其次；第二',
    'emotional impact': '情感影响',
    'Least rousing': '最不令人振奋的（least 最不；rousing adj. 激励人心的）',
    'rational argument': '理性论证（rational adj. 理性的）',
    'co-authors': 'n. 共同作者（co-author 的复数）',
    'play a bigger role': '发挥更大的作用',
    'probing': 'v. 探究；探查（probe 的现在分词）',
    'specific effects': '具体效果',
    'teaching style': '教学风格',
    'video exposure': '观看视频（exposure n. 接触； exposure to video）',
    'Meanwhile': 'adv. 与此同时',
    'had predicted': '曾预测（过去完成时，predict 的过去分词）',
    'eating his words': '食言；收回前言（eat one\'s words 固定搭配）',
}
