# -*- coding: utf-8 -*-
"""2022 Text 1 —— 加粗词/词组的悬浮释义。每个 bold 必须有释义。"""

GLOSS = {
    'On a recent sunny day': '在最近一个晴朗的日子里｜时间状语',
    'roam over': '在…漫步；闲逛（不及物，后接地点）',
    'windswept': 'adj. 被风吹拂的；开阔多风的',
    'rest': 'v. 休息；栖息',
    'in the shade of': '在…的阴影下',
    'parked': 'adj. 停放着的（park 的过去分词，此处作前置定语）',
    'drink water': '喝水',
    'with the cows': '和牛一起；伴随状语（with + 名词）',
    'random': 'adj. 随机的；随意的',
    'by design': '介词短语：故意地；经过设计的（by accident 的反义）',
    'bets': 'v. 押注；打赌（bet 的第三人称单数）',
    'climate- friendly': 'adj. 对气候友好的（原文 hyphen 后带空格，按提取原文保留）',
    'making their debut': '首次亮相；初次登场（debut n. 首次露面）',
    'labeled': 'v. 贴标签于；标注（label 的过去分词）',
    'regenerative agriculture': '再生农业｜恢复土壤健康的耕作方式',
    'trap greenhouse gases': '捕获温室气体（trap 此处为"截留、捕获"）',
    'marketed as': '作为…来营销；被当作…推销',
    'fight climate change': '对抗气候变化',
    'excited about': '对…感到兴奋（be excited about）',
    'harvests': 'v. 收割；收获（此处指"收集、获取"鸡蛋）',
    'cover crops': 'n. 覆盖作物｜保护土壤的植物',
    'draw worms and crickets': '吸引蚯蚓和蟋蟀（draw 此处为"吸引"）',
    'waste': 'n. 废物；排泄物（此处 the birds\' waste 指鸡粪）',
    'fertilizes': 'v. 施肥于；使肥沃（fertilize 的第三人称单数）',
    'allow': 'v. 使役动词：allow + 宾语 + to do 允许…做',
    'forage': 'v. 觅食；搜寻食物',
    'higher-quality': 'adj. 更高质量的',
    'supply to': '供应给…（supply sth. to sb.）',
    'push': 'n. 推动；推进（此处指行业的推动举措）',
    'premium offering': '高端产品（premium adj. 高端的、优质的）',
    'barely': 'adv. 仅仅；几乎不（barely more than 不过、仅仅）',
    'niche product': '小众产品；细分市场产品（niche n. 利基、细分市场）',
    'natural foods stores': '天然食品商店',
    'probiotics': 'n. 益生菌',
    'plant-based': 'adj. 植物基的；以植物为原料的',
    'exploded into': '爆发式增长为…；骤然成为（explode into）',
    'rollout': 'n. 推出；投放市场（产品上线）',
    'open the floodgates': '打开闸门；引发一连串（比喻放开限制）',
    'hard sell': '难卖的东西；强卖（a hard sell 指难以推销的商品/理念）',
    'tough to define': '难以定义（tough = 困难的）',
    'minimal': 'adj. 极少的；最小的',
    'improvement': 'n. 改善；改进',
    'though': 'conj. 尽管；虽然（此处引导让步状语从句）',
    'betting': 'v. 押注；断定（bet 的现在分词）',
    'premium attributes': '优质属性（premium adj. 优质的）',
    'free-range': 'adj. 自由放养的（家禽散养而非笼养）',
    'embrace sustainability': '接受/拥抱可持续性（embrace 此处为"欣然接受"）',
    'Surveys show': '调查显示（survey n. 调查）',
    'concerned about': '关注；担心（be concerned about）',
    'chalked up to': '归因于…；归功于（chalk up 原指记分，引申为"把…算作"）',
    'president': 'n. 总裁；会长；总统',
    'altering': 'v. 改变；改动（alter 的现在分词）',
    'food chain': '食物链',
    'beyond': 'prep. 超出；超过（此处 beyond what... 超出…的程度）',
}
