# -*- coding: utf-8 -*-
"""2022 Text 3 —— 加粗词/词组的悬浮释义。每个 bold 必须有释义。"""

GLOSS = {
    'encountered': 'v. 遇到；遭遇（encounter 的过去分词）',
    'personal': 'adj. 个人的；私人的',
    'professional lives': '职业生涯；职业生活（professional adj. 职业的）',
    'Think about': '想想；考虑（祈使句）',
    'tricked': 'v. 被骗；被欺骗（trick 的过去分词）',
    'frustrated': 'adj. 沮丧的；受挫的',
    'seamless': 'adj. 无缝的；顺畅的',
    'sign-up process': '注册过程（sign up 注册）',
    'cancel': 'v. 取消',
    'transparent': 'adj. 透明的；公开的',
    'complicated': 'adj. 复杂的（complicate 的过去分词作形容词）',
    'impair': 'v. 损害；削弱',
    'consumer choice': '消费者选择权',
    'examples': 'n. 例子；范例（example 的复数）',
    'dark patterns': '暗黑模式（操纵用户界面的欺骗性设计）',
    'First coined': '首次提出（coin 此处指"创造/提出"术语；过去分词作状语）',
    'catch-all term': '概括性术语；笼统说法（catch-all 包罗万象的）',
    'manipulate': 'v. 操纵；操控',
    'decision-making': 'n. 决策（decision 决定；making 做）',
    'users': 'n. 用户；使用者（user 的复数）',
    'identifies': 'v. 识别；确认（identify 的第三人称单数）',
    'common dark patterns': '常见的暗黑模式',
    'ranging from': '范围从…到…（range from...to... 现在分词作后置定语）',
    'hidden costs': '隐性成本；隐藏费用',
    'roach motel': 'n. 蟑螂旅馆（暗黑模式的一种：易进难出）',
    'In a 2019 study': '在 2019 年的一项研究中',
    'researchers': 'n. 研究人员（researcher 的复数）',
    'employs': 'v. 采用；使用（employ 的第三人称单数）',
    'Though widely prevalent': '尽管广泛流行（让步状语，省略主语和系动词）',
    'concept': 'n. 概念',
    'well understood': '被充分理解（被动；well 充分）',
    'Business and nonprofit leaders': '企业和非营利组织的领导者',
    'aware of': '意识到；知道（be aware of）',
    'avoid': 'v. 避免',
    'gray areas': '灰色地带；模糊不清的领域',
    'engender': 'v. 产生；引起',
    'ethical': 'adj. 道德的；伦理的',
    'persuasive': 'adj. 有说服力的',
    'the line between': '…之间的界限（line 此处指界限）',
    'engage in conversations': '展开对话；参与讨论（engage in 从事、参与）',
    'compliance': 'n. 合规；遵守',
    'privacy policy': '隐私政策',
    'experience designers': '用户体验设计师',
    'marketers': 'n. 营销人员（marketer 的复数）',
    'Any or all': '任何一个或全部',
    'play a role': '发挥作用；起作用',
    'digital deception': '数字欺骗（deception n. 欺骗）',
    'Lawmakers': 'n. 立法者（lawmaker 的复数）',
    'regulators': 'n. 监管机构；监管者（regulator 的复数）',
    'address': 'v. 解决；处理（此处指"应对"问题）',
    'ambiguity': 'n. 模糊性；模棱两可',
    'In March': '在三月',
    'the California Attorney General': '加州总检察长（美国州级司法长官）',
    'announced': 'v. 宣布（announce 的过去式）',
    'additional regulations': '附加法规；额外条例',
    'The regulations aim to': '这些法规旨在（aim to do 旨在做）',
    'ban': 'v. 禁止',
    'confusing language': '令人困惑的语言',
    'unnecessary steps': '不必要的步骤',
    'As more states': '随着更多州（as 引导从句）',
    'promulgating': 'v. 颁布；公布（promulgate 的现在分词）',
    'greater accountability': '更大的问责制（accountability n. 问责）',
    'addressed': 'v. 解决；处理（address 的过去分词）',
    'on a self- regulatory basis': '在自律的基础上（self-regulatory 自我监管的；原文提取带异常空格）',
    'hold themselves accountable': '对自己负责（accountable adj. 应负责任的）',
    'industry best practices': '行业最佳实践',
}
