# -*- coding: utf-8 -*-
"""2023 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'In the quest for': '在追求…的过程中（in the quest for）',
    'taking a shortcut': '走捷径（take a shortcut）',
    'paying the price': '付出代价（pay the price）',
    'square metres': '平方米（英式拼写）',
    'opposition': 'n. 反对（意见）',
    'banned': 'v. 禁止（ban 的过去分词）',
    'ethos': 'n. 理念；精神特质',
    'Royal Horticultural Society': '（英国）皇家园艺学会',
    'biodiversity': 'n. 生物多样性',
    'sustainability strategy': '可持续发展战略（sustainability 可持续性）',
    'in line with': '与…一致；符合',
    'alleviating flooding': '缓解洪涝（alleviate 缓解）',
    'cooling the environment': '冷却环境（现在分词短语）',
    'comes as': '正值…之际（come as...）',
    'raise awareness of': '提高对…的认识',
    'greenwash': 'n. 漂绿（伪环保宣传）',
    'followers': 'n. 关注者；粉丝',
    'petitions': 'n. 请愿书（petition）',
    'ecological damage': '生态破坏',
    'signatures': 'n. 签名（signature）',
    'point out': '指出；说明',
    'consume electricity': '消耗电力',
    'considerable amounts of': '大量的…',
    'lay fake grass': '铺设人造草（lay 铺）',
    'shrubs': 'n. 灌木（shrub）',
    'habitat for insects': '昆虫的栖息地（habitat 栖息地）',
    'In response to': '回应…；对…作出反应',
    'artificial grass': '人造草',
    'legislating on': '就…立法（legislate on）',
    'make the right choice': '做出正确选择',
    'comply with': '遵守；符合',
    'safeguards': 'n. 保障措施（safeguard）',
    'sustainable alternatives': '可持续的替代方案（alternative 替代品）',
}
