# -*- coding: utf-8 -*-
"""2023 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'capacity to do so': '做这件事的能力（capacity 能力）',
    'led a study': '主持了一项研究（lead a study）',
    'factoids': 'n. 小知识；冷知识（factoid）',
    'erased': 'v. 删除（erase 的过去分词）',
    'Guess what': '你猜怎么着（设问引出下文）',
    'made no effort to recall': '完全没有努力去回忆（make no effort to do）',
    'folders': 'n. 文件夹（folder）',
    'how to find': '如何找到（疑问词+不定式）',
    'deteriorating': 'v. 退化；恶化（deteriorate 的现在分词）',
    'adapting to': '适应…（adapt to）',
    'external hard drive': '外部硬盘',
    'cognitive offloading': '认知卸载（把记忆任务交给外界）',
    'fulfilled by': '由…承担/履行（be fulfilled by）',
    'may never': '可能永远不会（情态动词+否定副词）',
    'does': '（承前省略的动词）代替 remember',
    'destructive effect': '破坏性影响',
    'upside': 'n. 积极的一面；好处',
    'approach to learning': '学习的方式（approach to 对…的方法）',
    'conceptual thinking': '概念性思维（conceptual 概念的）',
    'intellectual value': '智力价值',
    'adding that': '并补充说…（现在分词作伴随状语）',
    'too soon to': '做…还为时过早（too... to）',
    'experimental evidence': '实验证据',
    'interferes with': '干扰；妨碍（interfere with）',
    'Simons': 'Simons（人名）',
    'surfing the web': '浏览网页（surf the web）',
    'computer-savvy': '精通计算机的（savvy 精通的）',
    'associated with': '与…相关联（be associated with）',
    'outweigh': 'v. 超过；胜过',
    'for the better': '向好的方向',
    'At this point': '目前；此时此刻',
}
