# -*- coding: utf-8 -*-
"""2023 Text 4 —— 加粗词/词组的悬浮释义。
每个 bold 项都必须有一条释义，否则 gen 会报 NO GLOSS。"""

GLOSS = {
    'paradoxical': 'adj. 矛盾的；看似矛盾却可能成立的',
    'detached': 'adj. 超然的；不带感情的｜此处指"语气平淡、不带情绪"',
    'express': 'v. 表达；表述',
    'paradox': 'n. 矛盾；悖论｜形容词 paradoxical',
    'In adolescence': '在青春期｜adolescence n. 青春期（约 10-19 岁）',
    'relied on': '依赖；依靠（rely on 的过去式）',
    'take care of': '照顾；照料',
    'compliant': 'adj. 顺从的；听话的',
    'rebellious': 'adj. 叛逆的；反抗的',
    'risk-takers': 'n. 冒险者｜take risks 冒险',
    'published': 'v. 发表；出版（publish 的过去分词，此处作后置定语）',
    'suggests': 'v. 表明；暗示（研究/数据"表明"，不是"建议"）',
    'go hand in hand': '相伴而生；密切相关',
    'a new wave of': '新一轮的…｜wave n. 浪潮、一波',
    'concentrated on': '集中于；专注于（concentrate on）',
    'policy makers': 'n. 政策制定者',
    'emphasizes': 'v. 强调；着重指出',
    'as well as': '既…又…；以及｜连接两个并列成分',
    'studied': 'v. 研究（study 的过去式，此处是动词不是"学习"）',
    'traits': 'n. 特质；特征（trait 的复数）',
    'ranging from': '范围从…到…（range from...to...）',
    'filled out': '填写（表格、问卷）',
    'questionnaires': 'n. 问卷；调查表',
    'altruistic': 'adj. 利他的；无私的',
    'sacrificing': 'v. 牺牲；舍弃（sacrifice 的现在分词）',
    'fades away': '逐渐消失；消退',
    'the same pattern': '同样的模式｜pattern n. 模式、规律',
    'holds for': '适用于；对…成立（hold for）',
    'more likely': '更有可能（be likely to do 很可能做）',
    'report': 'v. 报告；声称｜此处指问卷中"自述"',
    'unselfishly': 'adv. 无私地｜形容词 unselfish',
    'Most significantly': '最重要的是｜评注性状语，修饰全句',
    'positive correlation': '正相关｜统计学用语，两个变量同向变化',
    'develop together': '共同发展；一起发展',
    'common factor': '共同因素｜factor n. 因素',
    'underlies': 'v. 构成…的基础；是…的根本原因（underlie）',
    'contradictory': 'adj. 矛盾的；对立的',
    'is related to': '与…有关；与…相关',
    'reward sensitivity': '奖赏敏感性｜对奖励的反应强度，心理学概念',
    'involves': 'v. 涉及；需要（involve）',
    'balancing': 'v. 平衡；权衡（balance 的现在分词）',
    'benefits and costs': '收益与成本',
    'measures': 'v. 衡量；测量（measure）',
    'outweigh': 'v. 超过；比…更重要（out + weigh 重于）',
    'particularly sensitive': '尤其敏感｜be sensitive to 对…敏感',
    'social rewards': '社会性奖赏｜来自他人认可、社交成功的满足感',
    'impressing': 'v. 使印象深刻（impress 的现在分词）',
    'go up': '上升；增加',
    'risk-taking': 'n. 冒险（行为）',
    'Somehow': 'adv. 不知为何；以某种方式',
    'the effort of': '…所需的力气｜effort n. 努力、力气',
}
