# -*- coding: utf-8 -*-
"""2023 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'dismiss as': '把…视为（而不予理会）（dismiss A as B）',
    'chronic funding gap': '长期资金缺口（chronic 长期的）',
    'line up': '排成行；排队',
    'in crisis': '处于危机之中',
    'maintenance backlog': '维护积压（backlog 积压的工作）',
    'infrastructure': 'n. 基础设施',
    'crumbling': 'v. 破败；崩塌（crumble 的现在分词）',
    'privatizing': 'v. 私有化（privatize 的动名词）',
    'cure-all': 'n. 万能药；万灵丹',
    'a tiny portion': '一小部分（portion 份额）',
    'revenues': 'n. 收入（revenue）',
    'undercut': 'v. 削弱；损害',
    'commercial drumbeat': '商业鼓噪（drumbeat 鼓声，喻指持续的宣传）',
    'chronically starved of': '长期缺乏…（be starved of）',
    'taxpayers': 'n. 纳税人（taxpayer）',
    'kept intact': '保持完整（keep... intact）',
    'respondents': 'n. 受访者（respondent）',
    'additional taxes': '额外税款',
    'U.S. residents': '美国居民',
    'symbols of nature': '自然的象征',
    'carbon sequestration': '碳封存（sequestration 封存）',
    'contribution to': '对…的贡献',
    'jurisdictions': 'n. 司法管辖区（jurisdiction）',
    'to life': '（bring... to life）使…生动起来',
    'on a shoestring': '以极少的钱；小本经营',
    'allocates': 'v. 拨款；分配（allocate）',
    'flat since': '自…以来一直持平（flat 无变化的）',
    'annual visitors': '年游客量',
    'stands at': '（数值）达到/处于…',
}
