# -*- coding: utf-8 -*-
"""2024 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'In her new book': '在她她的新书中',
    'an economist at': '…（大学）的一名经济学家',
    'argues that': '认为；主张（argue 后接 that 宾语从句）',
    'Whatever we mean': '无论我们指的是什么（Whatever 引导让步状语从句）',
    'the gains': '收益；好处（gain 此处为名词复数）',
    'more evenly shared': '更均匀地分享（evenly 均匀地）',
    'gig workers': '零工工人（gig 短期工作、零活）',
    'undercut by automation': '被自动化削弱（undercut 削弱、暗中破坏）',
    'politically sustainable': '在政治上可持续的（sustainable 可持续的）',
    'Improving living standards': '提高生活水平（动名词短语作主语）',
    'boost productivity': '提高生产力（boost 推动、提升）',
    'says Coyle': 'Coyle 说（倒装引述分句）',
    "can't be expected to": '不能被期望做…（expect sb. to do 的被动式）',
    'if they': '如果他们…（if 引导条件状语从句）',
    'being destroyed': '被摧毁（现在分词被动式作宾语补足语）',
    'In a recent interview': '在最近的一次采访中',
    'roadblock': 'n. 障碍；路障',
    'deploying AI': '部署人工智能（deploy 部署）',
    'disruption': 'n. 颠覆；扰乱',
    'transformative technologies': '变革性技术（transformative 具有变革性的）',
    'business models': '商业模式',
    'tremendous changes': '巨大的变化（tremendous 巨大的）',
    'she adds': '她补充说',
    'social buy-in': '社会认同（buy-in 认同、支持）',
    'Instead': 'adv. 相反；反而',
    'resentment is simmering': '怨恨正在酝酿（simmer（感情）积蓄、酝酿）',
    'perceived to': '被认为（perceive 认为；be perceived to do）',
    'According to': '根据；按照',
    'roughly 38%': '大约 38%（roughly 大约）',
    'tech jobs': '科技工作岗位',
    'particularly concentrated': '尤其集中（concentrated 集中的）',
    'estimate': 'v. 估计；估算（后接 that 宾语从句）',
    'account for': '占据；解释（account for 占…比例）',
    'dominance': 'n. 主导地位（dominant 的名词）',
    'commercialization': 'n. 商业化',
    'soar': 'v. 猛增；飙升',
    'Not only': '不仅（置于句首引起部分倒装）',
    'foster': 'v. 助长；培养',
    'hold back': '阻碍；抑制',
    'lie in': '在于（lie in 位于、存在于）',
    'loosening': 'v. 放松；解开（loosen 的动名词）',
    'stranglehold': 'n. 束缚；扼制（stranglehold 勒脖子的控制）',
    'increased federal funding': '增加的联邦资金（increased 过去分词作定语）',
    'independent of': '独立于…（形容词短语作后置定语）',
    'tech giants': '科技巨头',
    'more immediate response': '更直接的应对（immediate 立即的、直接的）',
    'broaden': 'v. 拓宽；扩大',
    'expand opportunities': '扩大机会（expand 扩展）',
}
