# -*- coding: utf-8 -*-
"""2024 考研英语二 Text 4 —— 重点词/词组释义。
每个 bold 项都必须有一条释义，否则 gen 会报 NO GLOSS。"""

GLOSS = {
    'chances are': '很可能；大概是（固定搭配，后接从句）',
    'related to': '与…相关的（relate to 的过去分词短语）',
    'Whether': 'conj. 是否；不管…（是否）｜此处引导让步状语从句',
    'taking advantage of': '利用；趁…之机（take advantage of 的现在分词）',
    'keep better track of': '更好地追踪/掌握（keep track of 跟踪、记录）',
    'Recent research': '最近的研究｜research n. 研究',
    'Organization for the Review of Care and Health Applications': '健康与护理应用审查组织',
    'available on the market': '在市场上可获得的',
    'While': 'conj. 虽然；尽管（引导让步状语从句）｜也可表"当…时"',
    'it is not always clear': '并不总是清楚的（it is + 形容词 + 从句）',
    'collected, safeguarded and shared': '被收集、保护和共享（三个过去分词并列作被动谓语）',
    'Existing health privacy law': '现有的健康隐私法律',
    'primarily focused on': '主要关注于（be focused on）',
    'the way': '方式；…的方式（后常接省略 in which 的定语从句）',
    'health information': '健康信息',
    'tracking wearables': '追踪（数据的）可穿戴设备｜wearable n. 可穿戴设备',
    'legal protections': '法律保护｜legal adj. 法律的',
    'Without additional protections': '在没有额外保护措施的情况下（介词短语作条件状语）',
    'monetize': 'v. 使货币化；变现',
    'in a way': '以某种方式；在某种意义上',
    'In 2021': '在 2021 年（时间状语）',
    'faced': 'v. 面临；面对（face 的过去式）',
    'Federal Trade Commission': '联邦贸易委员会（美国机构，简称 FTC）',
    'The FTC': '联邦贸易委员会（Federal Trade Commission 的缩写）',
    'alleged': 'v. 声称；指控（allege 的过去式）',
    'despite express privacy claims': '尽管有明确的隐私声明（despite 介词，后接名词）',
    'settled the matter': '解决了此事（settle 解决争端）',
    'requiring': 'v. 要求（require 的现在分词，此处作后置定语）',
    'express affirmative consent': '明确的肯定同意｜express 明确的；affirmative 肯定的',
    'empowers': 'v. 授权；使能够（empower）',
    'initiate enforcement action': '采取/发起执法行动｜enforcement n. 执行、实施',
    'meaning': 'v. 意味着（mean 的现在分词，此处作结果/伴随定语）',
    'keeping their promises': '信守承诺（keep one\'s promise 遵守诺言）',
    'demonstrates': 'v. 表明；证明（demonstrate）',
    'As to the prospects': '至于…的前景（as to 关于、至于）',
    'commentators': 'n. 评论员；评论人士（commentator 的复数）',
    'in the short term': '在短期内',
    'implementing': 'v. 实施；执行（implement 的现在分词）',
    'shore up': '加强；支撑；巩固',
    'consumer-generated': '消费者生成的（consumer-generated 由消费者产生的）',
    'at the forefront of': '处于…的前沿；走在…最前列',
    'with the California Consumer Privacy Act': '凭借/伴随《加利福尼亚州消费者隐私法》（with 复合结构作状语）',
    'recently passed': '最近通过的（recently 最近；pass 通过）',
    'state consumer data privacy legislation': '州消费者数据隐私立法｜legislation n. 法律、立法',
}
