# -*- coding: utf-8 -*-
"""2024 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'construction crisis': '建筑危机（construction 建筑）',
    'because of': '因为；由于（介词短语）',
    'has warned': '已警告（warn 警告；现在完成时）',
    'trade body': '行业协会（body 机构、团体）',
    'has called for': '已呼吁（call for 呼吁、要求）',
    'urgent action': '紧急行动（urgent 紧急的）',
    'Currently': 'adv. 目前；当前',
    'home-grown': 'adj. 本国种植的；本土生产的',
    'net importer': '净进口国（net 净的）',
    'Coming at a time of': '正值…之际（come at a time of）',
    'go far enough': "足够深入；力度足够（常用于否定：don't go far enough 力度不够）",
    'fail to promote': '未能宣传（fail to do 未能做）',
    'Not only': '不仅（置于句首引起部分倒装）',
    'carbon crisis': '碳危机',
    'chief executive of': '…的首席执行官（CEO）',
    'For decades': '几十年来',
    'taken responsibility for': '承担起…的责任（take responsibility for）',
    'fluctuating prices': '波动的价格（fluctuate 波动）',
    'ideal conditions': '理想条件',
    'low-carbon homes': '低碳住宅',
    'sustainably managed': '得到可持续管理的（sustainably 可持续地）',
    'three quarters': '四分之三',
    'built from': '用…建造（build from）',
    'home-grown wood': '国产木材',
    'complex': 'adj. 复杂的',
    'range from': '（范围）从…到…（range from... to...）',
    'outdated perceptions': '过时的认知（outdated 过时的）',
    'encompasses': 'v. 包含；涉及（encompass）',
    'significant hesitation': '明显的犹豫（hesitation 犹豫）',
    'on behalf of': '代表…；出于…（此处指「农民和土地所有者方面的」）',
    'productive tree planting': '生产性植树（productive 生产性的）',
    'deliver': 'v. 带来；提供（deliver benefits 带来好处）',
    'net-zero strategy': '净零排放战略',
    'added': 'v. 补充说（add 的过去式）',
    'of critical importance': '至关重要（of + 抽象名词 = 形容词作用）',
    'secure supplies': '稳定的供应（secure adj. 稳固的、可靠的）',
    'has stated': '已表明（state 陈述、声明）',
    'ambition': 'n. 雄心；抱负',
    'little action': '很少的行动（little 表否定意味）',
    'calling for': '呼吁（call for 的现在分词）',
    'impetus': 'n. 推动力；促进',
    'meet increasing demand': '满足不断增长的需求（meet demand 满足需求）',
}
