# -*- coding: utf-8 -*-
"""2024 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'One of the biggest challenges': '最大的挑战之一',
    'convincing them that': '说服他们…（convince sb. that）',
    'turn over the keys': '交出钥匙（turn over 移交）',
    'life-changer': 'n. 彻底改变生活的事物',
    'forced to stop': '被迫停止（force sb. to do 的被动式）',
    'former risk manager': '前风险管理人员（former 前任的）',
    'Menke': 'Menke（人名）',
    'advises physicians that': '建议医生…（advise sb. that 双宾语结构）',
    'substantial driving impairment': '严重的驾驶障碍（impairment 损伤、障碍）',
    'it is desirable and ethical to': '做…是可取且合乎道德的（it 形式主语）',
    'require physicians to report': '要求医生报告（require sb. to do）',
    'mandate reports': '强制要求报告（mandate 强制）',
    'a breach of confidentiality': '违反保密义务（breach 违反；confidentiality 保密性）',
    'liability and penalties': '责任与处罚（liability 法律责任）',
    'in accordance with': '依照；与…一致',
    'counseled': 'v. 建议；劝告（counsel 的过去式）',
    'Part of the problem': '问题的一部分',
    'addressed piecemeal': '被零散地处理（piecemeal 零散地）',
    'gerontologist': 'n. 老年学家（gerontology 老年学）',
    'National Institute': '国家（研究）所',
    'better evidence on': '关于…的更好证据（evidence on 关于…的证据）',
    'what makes drivers unsafe': '是什么让驾驶员不安全（what 引导宾语从句）',
    'does seem to work': '确实似乎有效（does 强调）',
    'requiring drivers to': '要求驾驶员…（require sb. to do）',
    'license renewal': '驾照更新/换领（renewal 续期）',
    'Mandatory in-person renewal': '强制性亲自换领（mandatory 强制的）',
    'associated with': '与…相关（be associated with）',
    'fatal crashes': '致命车祸（fatal 致命的）',
    'Passing vision tests': '通过视力测试（动名词短语作主语）',
    'a similar decline': '类似的下降',
    'no benefit from': '没有来自…的益处',
    'eye doctors': '眼科医生',
    "can't afford to": '负担不起（afford to do）',
    'have their hands full': '忙得不可开交（固定习语）',
    'follow through with': '跟进；坚持完成',
    'have trouble driving': '开车有困难（have trouble doing）',
    'As long as': '只要（引导条件状语从句）',
    'self-driving cars': '自动驾驶汽车',
    'crashes': 'n. 车祸；碰撞',
    'posed by': '由…造成的（pose 构成、引起）',
    'algorithms': 'n. 算法（algorithm 的复数）',
    'improve safety': '提高安全性',
    '100-year lives': '百岁人生',
    'comfortably': 'adv. 舒适地；轻松地',
}
