# -*- coding: utf-8 -*-
"""2025 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'historically tipped': '历来给…小费（tip v. 给小费）',
    'restaurant servers': '餐厅服务员',
    'minimum wage': '最低工资',
    'a wide range of': '各种各样的；大范围的',
    'processing purchases': '处理交易/结账（process v. 处理）',
    'digital payment systems': '数字支付系统',
    'prompted customers to': '提示/促使顾客做…（prompt sb. to do）',
    'not connected to': '与…脱节/不相关（be connected to）',
    'salary and service norms': '薪资与服务规范（norm 规范）',
    'when and how people tip': '人们何时以及如何给小费（宾语从句）',
    'nearly always': '几乎总是',
    'receiving a service': '接受服务（receive）',
    'haircut': 'n. 理发',
    'reward': 'v. 奖励；回报',
    'incentive': 'n. 激励；动力',
    'more common': '更常见',
    'beforehand': 'adv. 事先；预先',
    'automatically add tips': '自动添加小费',
    'prevalence': 'n. 普及；盛行',
    'made it easier': '使…更容易（make it + adj. + to do）',
    'creeping into': '悄悄渗入；逐渐蔓延（creep into）',
    'routinely': 'adv. 常规地；惯常地',
    'default options': '默认选项',
    'risen from': '从…上升（rise from A to B）',
    'or higher': '或更高',
    'tipflation': 'n. 小费通胀（作者造词：tip + inflation）',
    'expectation': 'n. 预期；期待',
    'a vital source of income': '重要的收入来源（vital 至关重要的）',
    'tipped minimum wage': '小费最低工资（美国对可获小费岗位的特殊最低工资）',
    'as low as': '低至',
    'supplementing': 'v. 补充（supplement）',
    'low-wage service workers': '低薪服务业员工',
    'Notably': 'adv. 值得注意的是',
    'primarily benefits': '主要惠及（primarily 主要地）',
    'waiters': 'n. 服务员（侍者）',
    'banned tipping': '禁止收小费（ban 禁止）',
    'fizzled out': '不了了之；逐渐失败（fizzle out）',
    'succumbing to': '屈服于（succumb to）',
    'temptations': 'n. 诱惑（temptation 的复数）',
    'frustrated': 'adj. 沮丧的；懊恼的',
    'too high of a tip, too often': '小费过高、频率过高',
    'coercive': 'adj. 强制性的；胁迫的',
    'dissociated from': '与…脱节（be dissociated from）',
}
