# -*- coding: utf-8 -*-
"""2025 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'proliferating': 'v. 激增；迅速扩散（proliferate）',
    'spells out': '明确规定；详细说明（spell out）',
    'issue heat warnings': '发布高温警报（issue 发布）',
    'calls for': '要求；呼吁（call for sb. to do）',
    'set aside': '预留；拨出',
    'heatstroke': 'n. 中暑',
    'implementation': 'n. 实施；执行',
    'uneven': 'adj. 不均衡的；参差不齐的',
    'adequate funding': '充足的资金（adequate 充分的）',
    'triggering thresholds': '触发阈值（threshold 阈值）',
    'customized to': '按…定制（customize）',
    'adequate trigger': '充分的触发条件',
    'humidity': 'n. 湿度',
    'gauge of risk': '风险的衡量指标（gauge 计量标准）',
    'heatstroke deaths': '中暑死亡事件',
    'nuanced and localized': '更细致且本地化的（nuanced 有细微差别的）',
    'shy of': '差…不到；未达到（1°C shy of 差 1°C）',
    'threshold': 'n. 阈值；门槛',
    'meteorological': 'adj. 气象的',
    'amplified': 'v. 放大；加剧（amplify 的过去分词）',
    'neglected factor': '被忽视的因素（neglect 忽视）',
    'shade': 'n. 阴凉；遮阴',
    'urban planner': '城市规划师',
    'model plan': '示范计划（model 典范的）',
    'best practices': '最佳实践',
    'vulnerability map': '脆弱性地图（vulnerability 脆弱性）',
    'most at risk': '风险最高的（后置定语）',
    'mapping': 'n. 地图绘制',
    'key parameters': '关键参数（parameter 参数）',
    'elderly population': '老年人口',
    'informal dwellings': '非正式住所（dwelling 住处）',
    'cooling centers': '降温中心',
    'in the event of': '在…发生的情况下；一旦',
    'heat wave': '热浪',
    'emergency responses': '应急响应',
    'medium- to long-term measures': '中长期措施',
    'advise': 'v. 建议；向…提供咨询',
    'provide shade': '提供遮阴',
    'retrofit': 'v. 改造；翻新',
    'building regulations': '建筑法规',
    'target': 'n. 目标',
}
