# -*- coding: utf-8 -*-
"""2025 考研英语二 Text 4 — 重点词释义。"""

GLOSS = {
    'desire paths': '欲望路径（行人踩出来的捷径）',
    'unofficial footprints': '非官方的足迹',
    'unspoken preferences': '未言明的偏好（unspoken 未经明说的）',
    'trodden dirt tracks': '被踩踏出来的泥土小径（trodden 踩踏的）',
    'collective disobedience': '集体违规（disobedience 不服从）',
    'cut corners': '抄近路；走捷径',
    'interpret': '把…解读为（interpret A as B）',
    'valuable insights': '宝贵的见解（insight 洞见）',
    'dynamics': 'n. 动态关系',
    'the Oval': '椭圆形草坪（俄亥俄州立大学校园内的场地名）',
    'pave': 'v. 铺设（路面）',
    'reluctance': 'n. 不情愿；犹豫',
    'integrate': '把…纳入（integrate A into B）',
    'aesthetics': 'n. 美观；美学',
    'devoted to': '专门用于…的（过去分词作定语）',
    'adhere to designated walkways': '遵守指定人行道（adhere to 遵守）',
    'inherent in': '…所固有的（形容词短语作后置定语）',
    'clash': 'n. 冲突',
    'user-driven': '用户驱动的（-driven 由…驱动）',
    'visually curated': '在视觉上精心策划的（curate 策划）',
    'Native Americans': '美洲原住民',
    'settlements': 'n. 定居点（settlement）',
    'Dutch colonists': '荷兰殖民者',
    'trade roads': '贸易道路',
    'renamed': 'v. 重新命名（rename 的过去分词）',
    'defies': 'v. 违背；抗拒（defy 的三单）',
    'grid-based system': '网格系统（grid 网格）',
    'diagonal': 'n. 对角线；斜线',
    'sparked': 'v. 引发；激起（spark）',
    'fascination': 'n. 迷恋；着迷',
    'hub': 'n. 中心；枢纽',
    'a wide array of': '各种各样的（array 一系列）',
    'little-known': '鲜为人知的',
    'alternate routes': '替代路线（alternate 备选的）',
    'forging': 'v. 开辟；锻造（forge）',
    'adaptability': 'n. 适应性（adapt 的名词）',
    'criss-cross': 'v. 纵横交错',
    'unconventional routes': '非常规路线',
    'communal choice': '共同选择（communal 公共的、共有的）',
}
