# -*- coding: utf-8 -*-
"""2025 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'visionary': 'adj. 有远见的',
    'high-quality, timely care': '高质量、及时的医疗服务（timely 及时的）',
    'out of date': '过时的',
    'Nearly 75 years on': '近 75 年过去了（time+on 表时间推移）',
    'life expectancy': '预期寿命',
    'infant mortality': '婴儿死亡率（mortality 死亡率）',
    'lagging behind': '落后于（lag behind）',
    'waitlists': 'n. 候诊名单（waitlist）',
    'inaccessible': 'adj. 难以获得的（accessible 的否定）',
    'squeezing out': '挤占；排挤（squeeze out）',
    'breaking point': '崩溃点；极限（breaking 动名词作定语）',
    'acute': 'adj. 严峻的；尖锐的',
    'well rehearsed': '被反复讨论过的；老生常谈的（rehearse 排练）',
    'reducing and diverting demand': '减少和分流需求（divert 转移）',
    'rather than': '而不是',
    'primary care': '基层医疗/初级保健',
    'reliance on': '对…的依赖（rely on 的名词形式）',
    'social care': '社会护理（养老、照护等）',
    'capacity': 'n. 能力；容量',
    'long-term conditions': '长期病/慢性病',
    'Yet despite': '然而尽管（despite 介词接名词）',
    'meaningful progress': '实质性进展',
    'think tank': '智库',
    'launching': 'v. 启动；发起',
    'entitled': '命名为…的（过去分词作定语）',
    'calling for': '呼吁（call for）',
    'urgent rethink': '紧急反思（rethink 反思）',
    'hospital-centric': '以医院为中心的（-centric 以…为中心）',
    'maximise': 'v. 最大化（英式拼写）',
    'It is estimated': '据估计（形式主语句型）',
    'accounts for': '占据（比例）；解释',
    'socialise': 'v. 社交（英式拼写）',
    'cross- government strategy': '跨政府部门的战略（cross- 跨）',
    'social determinants': '社会决定因素（determinant 决定因素）',
    'scrapped': 'v. 废弃（scrap 的过去分词）',
    'price tag': '代价；价签',
    'diabetes': 'n. 糖尿病',
    'distributed': 'v. 分配（distribute 的过去分词）',
    'health functions': '卫生职能',
    'local leaders': '地方领导者',
}
