# -*- coding: utf-8 -*-
"""2026 考研英语二 Text 2 — 重点词释义。"""

GLOSS = {
    'one in five': '五分之一',
    'looking for guidance': '寻求指导（现在分词作伴随状语）',
    'engaging with': '与…互动（engage with）',
    'feeling heard': '感到被倾听（leave sb. feeling 宾补）',
    'isolated': 'adj. 孤独的；孤立的',
    'newfound': 'adj. 新建立的；新获得的',
    'confidential information': '机密信息（confidential 机密的）',
    'keeping our secrets': '保守我们的秘密（keep a secret）',
    'implications': 'n. 影响；后果（implication）',
    'for example': '例如',
    'broad rights': '广泛的权利',
    'sees fit': '认为合适（see fit to do 的省略）',
    'third parties': '第三方',
    'potentially be exposed': '可能被暴露（expose 曝光）',
    'taking note': '注意到（take note）',
    'outright ban': '完全禁止（outright 彻底地）',
    'regulate': 'v. 规范；管制',
    'in place': '到位的；就位的（后置定语）',
    'break the rules': '违反规定',
    'productivity': 'n. 生产力；效率',
    'human colleagues': '人类同事',
    'delicate balance': '微妙的平衡',
    'leveraging': 'v. 利用（leverage）',
    'data exposure': '数据泄露',
    'with the same level of care': '以同样程度的谨慎',
    'knowledge gap': '知识差距',
    'ownership': 'n. 所有权',
    'instilling': 'v. 灌输（instill）',
    'evolve with': '随…演变',
    'AI landscape': 'AI 格局（landscape 此处为比喻）',
    "it's up to us": '由我们负责；取决于我们',
    'compromising our privacy': '损害我们的隐私（compromise 妥协、危害）',
    'back away from': '从…退缩；回避',
    'as long as': '只要（引导条件状语从句）',
    'equipped with': '配备有…（be equipped with）',
    'the challenge lies': '挑战所在（lie in 位于）',
    'advertising and marketing budgets': '广告与营销预算',
    'fall victim': '沦为受害者（fall victim to）',
    'digital responsibility': '数字责任',
    'spilling the beans': '泄密（spill the beans 习语：说漏嘴）',
}
