# -*- coding: utf-8 -*-
"""2026 考研英语二 Text 3 — 重点词释义。"""

GLOSS = {
    'preferred means of travel': '首选的出行方式（means 方式，单复数同形）',
    'locals and tourists alike': '本地人和游客都（alike 同样地）',
    'cover': 'v. 行驶完（一段距离）',
    'connects': 'v. 连接（connect）',
    'the best option': '最佳选择',
    'leisure and business travellers': '休闲旅客和商务旅客',
    'maintenance works': '维护工程（works 工程）',
    'into chaos': '陷入混乱（throw... into chaos）',
    'accounts for': '占据（比例）',
    'Disruptions': 'n. 中断；扰乱（disruption 的复数）',
    'a fixture in': '…中固定出现的事物（fixture 固定物）',
    'publicly controlled': '公共控股的（publicly 以公共方式）',
    'train operator': '列车运营商',
    'obsolete infrastructure': '陈旧的基础设施（obsolete 过时的）',
    'partly': 'adv. 部分地',
    'recovery fund': '复苏基金',
    'beneficiary': 'n. 受益方',
    'planned investments': '计划中的投资',
    'a total of': '总计',
    'lack of capacity': '运力不足（capacity 容量、运力）',
    'Transport economist': '交通经济学家',
    'in the meantime': '在此期间；同时',
    'inevitable': 'adj. 不可避免的',
    'mixed system': '混合系统',
    'spare capacity': '备用运力（spare 备用的）',
    'hiccup': 'n. 小问题；小故障（原义打嗝）',
    'means that': '意味着…（后接宾语从句）',
    'regular tracks': '普通轨道（regular 常规的）',
    'congestion': 'n. 拥堵',
    'breaks down': '发生故障（break down）',
    'is affected': '受到影响（被动语态）',
    'segregation': 'n. 分离；隔离',
    'urban centres': '城市中心（英式拼写 centres）',
    'underground rail links': '地下铁路连接线',
    'high-density technology': '高密度技术',
    'satellite signalling': '卫星信号系统（signalling 英式拼写）',
    'allow for': '使…成为可能；允许',
    'at any given time': '在任何给定时间',
    'traffic fluidity': '交通流畅性（fluidity 流动性）',
}
