# -*- coding: utf-8 -*-
"""2026 考研英语二 Text 4 — 重点词释义。"""

GLOSS = {
    'beloved': 'adj. 深受喜爱的',
    'street festivals': '街头节日',
    'community leader': '社区领袖',
    'blossomed into': '发展成为（blossom into）',
    'abruptly shutting down': '突然停办（abruptly 突然地；shut down 关闭）',
    'pointed to': '指出（point to）',
    'declining attendee donations': '不断下降的参与者捐款（attendee 参与者）',
    'highlighting': 'v. 凸显（现在分词作补充说明）',
    'skyrocketed': 'v. 飞涨（skyrocket 的过去分词）',
    'portable restrooms': '便携式卫生间',
    'staffing': 'n. 人员配备',
    'dropped dramatically': '大幅下降（dramatically 急剧地）',
    'economic engines': '经济引擎',
    'as a whole': '整体上',
    'drive foot traffic': '带来客流量（foot traffic 人流量）',
    'cultural vibrancy': '文化活力（vibrancy 活力）',
    'solicit donations': '请求捐款（solicit 请求、募集）',
    'no city funding': '没有市政拨款',
    'sponsorships': 'n. 赞助（sponsorship）',
    'vendor fees': '摊位费（vendor 摊主）',
    'most anticipated': '最受期待的（anticipate 期待）',
    'drawing upward of': '吸引超过…（draw 吸引；upward of 超过）',
    'vendors': 'n. 摊主；商贩（vendor）',
    'record-breaking attendance': '创纪录的参与人数',
    'the turnout': '参与人数；到场人数',
    'lowest point': '最低点',
    'scale back': '缩减；缩小规模',
    'footprint': 'n. 规模；占地面积',
    'eliminating': 'v. 取消；消除（eliminate）',
    'striving to keep': '努力保持（strive to do）',
    'come to expect': '逐渐期待（come to do 逐渐…）',
    'community support': '社区支持',
    'thriving': 'adj. 繁荣的；兴旺的（thrive 的现在分词）',
    'chip in': '共同出力；凑钱',
    "doesn't happen by accident": '不是偶然发生的（by accident 偶然）',
}
