# -*- coding: utf-8 -*-
"""2026 考研英语二 Text 1 — 重点词释义。"""

GLOSS = {
    'springs to mind': '浮现在脑海中（spring to mind）',
    'old-fashioned': 'adj. 过时的',
    'seaside town': '海滨小镇',
    "aren't they all closing": '它们不都在关闭吗？（否定疑问）',
    'startlingly': 'adv. 惊人地（startling 令人吃惊的）',
    'commissioned me to': '委托我做…（commission sb. to do）',
    'independent review': '独立审查',
    'up and down the country': '全国各地',
    'more than twice the number of': '…数量的两倍多',
    'a hive of activity': '一片繁忙的景象（hive 蜂巢）',
    'a multitude of': '众多的（multitude 大量）',
    'intellectual property': '知识产权',
    'entrepreneurs': 'n. 创业者（entrepreneur）',
    'on site': '在现场',
    'health checks': '健康检查',
    'Fifa-standard': '符合国际足联标准的',
    'free': 'adv. 免费',
    'In return for': '作为…的回报',
    'precisely nothing': '分文不取（precisely 恰好、完全）',
    'no charge': '不收费',
    'justify': 'v. 证明…有理；为…辩解',
    'welcomed in': '受到欢迎（welcome in 迎进门）',
    'institution': 'n. 机构',
    'public or private': '无论公共还是私人的',
    'overlooked and underappreciated': '被忽视和低估（over- / under- 前缀）',
    'overall decline': '总体下降',
    'financial pressure': '财政压力',
    'disputed': 'adj. 有争议的（dispute 争论）',
    'annual survey': '年度调查',
    'official statistics': '官方统计数据',
    'of course': '当然',
    'too many': '太多了（230 libraries too many 多出 230 家）',
    'future generations': '子孙后代',
    'raise awareness of': '提高对…的认识',
    'branding campaign': '品牌宣传活动',
    'physical presence': '实体存在感',
    'automatic memberships': '自动会员资格',
    'end up losing': '最终失去（end up doing）',
    'for some time': '有很长一段时间',
}
